import {orderTargets,automaticOrders,targetHint} from './order-targets.mjs';
import {dialogueHTML,dialogueFor} from './dialogue.mjs';
import {PROLOGUE,storyFor} from './stories.mjs';
import {terrain} from './terrain.mjs';
import {geometry} from './navigation.mjs';
import {nearbyUnits} from './map-layout.mjs';
import {stepsFor,ensureGuide,stepComplete,refreshGuide,nextStep} from './tutorial.mjs';
import {newGame,updateObservations,battleReport,locations,LOCS,TYPES,FORMATIONS,ORDERS,issue,tick,targets,commandTargets,visible,spy,surrender,withdraw,log} from './engine.mjs';
const $=id=>document.getElementById(id), $$=s=>[...document.querySelectorAll(s)],fmt=n=>Math.round(n).toLocaleString('zh-TW'),clock=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
let g=newGame(), selected='a1',tab='intel',showIntel=true,showGrid=true,endedShown=false,lastPaint=0,lastSave=0,toastTimer,mapPick=null,modalPaused=false,guideKey='',guideNotice='',mapInteraction=false;
const icons={heavy:'重',spear:'槍',bow:'弓',light:'斥',horse:'騎',engineer:'工'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const own=()=>g.units.filter(u=>u.side===g.role), unit=()=>g.units.find(u=>u.id===selected);
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500);}
function save(silent=false){try{localStorage.setItem('siege-qingshi-v1',JSON.stringify(g));$('saveStatus').textContent=`已存檔 ${clock(g.t)}`;if(!silent)toast('戰局已儲存於此瀏覽器');}catch{if(!silent)toast('此瀏覽器無法儲存，請勿關閉戰局。');}}
function select(id){selected=id;options();const u=unit();$('formation').value=u.formation;$('stance').value=u.stance;$('equipment').value=u.equipment;$('retreatAt').value=String(u.retreatAt);render();}
let targetSignature='',targetContext='';
function choices(){return orderTargets(g,selected,$('action').value,mapPick);}
function choicesSignature(){return JSON.stringify([selected,$('action').value,choices().map(p=>[p.id,p.name]),commandTargets(g).filter(p=>p.unitId).map(p=>p.id)]);}
function options(){const action=$('action').value,context=selected+':'+action,changed=context!==targetContext,prev=$('target').value,known=choices(),automatic=automaticOrders.includes(action);const groups=[['友軍 · 掩護對象',known.filter(p=>p.allyId)],['可見敵軍',known.filter(p=>p.unitId)],['位置與設施',known.filter(p=>!p.allyId&&!p.unitId)]];
$('target').innerHTML=groups.filter(([,items])=>items.length).map(([label,items])=>`<optgroup label="${label}">${items.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</optgroup>`).join('');
if(automatic||!known.length)$('target').innerHTML=`<option value="">${automatic?'自動決定 · 不需選擇':'目前沒有適用目標'}</option>`;
else if(prev&&!known.some(p=>p.id===prev)&&!changed){$('target').insertAdjacentHTML('afterbegin','<option value="" disabled>原目標已失效，請重新選擇</option>');$('target').value='';}
else $('target').value=known.some(p=>p.id===prev)?prev:known[0].id;
$('target').disabled=automatic||!known.length;$('targetHint').textContent=targetHint(action);$('targetHint').title=targetHint(action);$('target').title=targetHint(action);
const enemies=commandTargets(g).filter(p=>p.unitId),ambush=$('ambushEnemy').value;$('ambushEnemy').innerHTML='<option value="">任意進入的敵軍</option>'+enemies.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');if(ambush&&!enemies.some(p=>p.id===ambush))$('ambushEnemy').insertAdjacentHTML('beforeend',`<option value="${esc(ambush)}" disabled>先前指定敵軍已失聯</option>`);$('ambushEnemy').value=ambush;targetContext=context;targetSignature=choicesSignature();}

function readOrder(){return {formation:$('formation').value,stance:$('stance').value,equipment:$('equipment').value,retreatAt:Number($('retreatAt').value),enemyId:$('action').value==='ambush'?($('ambushEnemy').value||null):null};}
function send(queue=false,extra={}){const target=automaticOrders.includes($('action').value)?null:$('target').value==='custom'?mapPick:$('target').value;if(issue(g,selected,$('action').value,target,{...readOrder(),queue,...extra})){toast(queue?'協同計畫已加入軍令簿':'軍令已交付傳令兵；恢復時間後開始傳達。');render();}else if(g.orderError)modal(`<h2>無法執行軍令</h2><p>${esc(g.orderError)}</p><button data-close>返回修改</button>`);else toast($('action').value==='encircle'?'封鎖請選東、西、南、北四座城門。':$('action').value==='intercept'?'攔截請指定一支目前可見的敵軍。':$('action').value==='ambush'?'埋伏請選擇一個地點；指定伏擊對象必須目前可見。':'無法傳令：請確認部隊可受令，且指定敵軍仍在視野中。');}
function roster(){if(mapInteraction)return;const total=own().reduce((n,u)=>n+u.n,0);$('troops').textContent=fmt(total);$('losses').textContent=`傷亡 ${fmt(own().reduce((n,u)=>n+u.loss,0))}`;$('unitCount').textContent=`${own().filter(u=>u.n>0).length} 營`;$('roster').innerHTML=own().map(u=>`<button class="unit-card ${selected===u.id?'selected':''}" data-unit="${u.id}" aria-label="選取${u.name}，${fmt(u.n)}人，士氣${Math.round(u.morale)}，疲勞${Math.round(u.fatigue)}"><span class="unit-icon">${icons[u.type]}</span><span><span class="unit-heading"><span>${u.name.replace(/第[一二三四五六]/,'')}</span><strong>${fmt(u.n)}</strong></span><span class="unit-status"><span>${u.pending.length?'◷ 傳令 '+Math.max(0,Math.ceil(u.pending[0].eta-g.t))+'秒':u.status}</span><span>${Math.round(u.morale)} · ${Math.round(u.fatigue)}</span></span>${u.engagingId?`<span class="unit-opponent">⚔ ${esc(knownName(u.engagingId))}</span>`:u.engagingWallId?`<span class="unit-opponent">攻城：${g.walls.find(w=>w.id===u.engagingWallId)?.name}</span>`:''}<span class="bars"><span class="bar"><i style="width:${u.morale}%"></i></span><span class="bar fatigue"><i style="width:${u.fatigue}%"></i></span></span></span></button>`).join('');}
function renderIntel(){updateObservations(g);let html='';if(tab==='intel'){
 if(g.role==='attack')html=['east','south','west','north'].map(id=>{const i=g.intel[id],age=Math.max(0,Math.floor((g.t-i.time)/60));return `<article class="intel-card"><div class="intel-title"><h3>${locations(g)[id].name}</h3><small>${age===0?'剛剛確認':age+' 分鐘前'}</small></div><div class="intel-number">${fmt(i.low)}–${fmt(i.high)}<small>人 · 估計</small></div><div class="intel-line"><span>士氣</span><span>${i.morale||'尚未確認'}</span></div><div class="intel-line"><span>情報可信度</span><span class="stars">${'★'.repeat(Math.max(1,i.confidence-Math.floor(age/5)))}${'☆'.repeat(5-Math.max(1,i.confidence-Math.floor(age/5)))}</span></div><div class="intel-note">${i.note}</div></article>`}).join('');
 else html=`<article class="intel-card"><div class="intel-title"><h3>攻軍兵力</h3><small>初始斥候報告</small></div><div class="intel-number">4,000–5,500<small>人</small></div><p class="intel-note">敵軍沿南方道路進軍。其主糧營在河流以南，可派部隊出城火攻。</p></article>`+g.walls.map(w=>`<article class="intel-card"><div class="intel-title"><h3>${w.name}</h3><small>我方城防</small></div><div class="intel-number">${Math.round(w.hp)}<small>% 完整度</small></div></article>`).join('');
 if(g.role==='attack')html+=g.walls.map(w=>{const k=g.wallIntel?.[w.id];return `<article class="intel-card"><div class="intel-title"><h3>${w.name} · 城防</h3><small>${k?(g.t-k.time<1?'目前目視':clock(k.time)+' 回報'):'未觀測'}</small></div><div class="intel-number">${k?Math.round(k.hp)+'%':'未知'}<small>耐久</small></div>${k&&g.t-k.time>=1?'<p>離開視野，數值為最後已知耐久。</p>':''}</article>`;}).join('');
 }else if(tab==='combat')html=combatReport();else if(tab==='logs')html=g.logs.map(l=>`<div class="log ${l.type}"><small>${clock(l.t)}</small><br>${esc(l.text)}</div>`).join('');
 else html=own().flatMap(u=>{const items=[];if(u.pending[0])items.push(`<div class="plan-item"><strong>${u.name} · 傳令中</strong>${ORDERS[u.pending[0].action]} ${esc(u.pending[0].target?.name||'')}<br>抵達倒數 ${Math.max(0,Math.ceil(u.pending[0].eta-g.t))} 秒</div>`);if(u.order)items.push(`<div class="plan-item"><strong>${u.name} · ${u.status}</strong>${ORDERS[u.order.action]} ${esc(u.order.target?.name||'')}<br>${FORMATIONS[u.formation]} · 士氣低於 ${u.retreatAt}% 撤退</div>`);u.plan.forEach((o,i)=>items.push(`<div class="plan-item"><button data-cancel="${u.id}:${i}">取消</button><strong>${u.name} · 計畫 ${i+1}</strong>${ORDERS[o.action]} ${esc(o.target?.name||'')}<br>${o.trigger==='now'?'前一命令完成':o.trigger==='time'?'目前命令開始後':`${g.units.find(v=>v.id===o.triggerUnit)?.name||'友軍'}${o.trigger==='arrived'?'抵達後':'交戰後'}`} ${o.wait||0} 秒</div>`));return items;}).join('')||'<p class="empty">軍令簿尚無計畫。<br>選取部隊，在下方設定命令；你也能安排抵達或交戰後執行的協同行動。</p>';
 if(tab==='intel'&&g.level!==3)html+=`<article class="intel-card"><h3>河道通行</h3><p>石橋：${Math.round(g.bridges?.bridge??100)}% · 浮橋：${Math.round(g.bridges?.pontoon??0)}%</p><p>100% 才可通行；${g.level===2&&g.t<480?'淺灘洪水封路，08:00 退水。':(g.mapRevision===2?'西端淺灘可繞行。':'東方淺灘可繞行。')}</p></article>`;if(tab==='intel'&&g.level===3)html+=`<article class="intel-card"><h3>合圍優勢</h3><p>有效封鎖 ${g.blockadedGates||0} / 4 門</p><p>三門合圍：${Math.floor(g.isolation||0)} / 120 秒</p><p>每封一門可截取補給；封鎖部隊承傷降低 35%，逐步恢復疲勞。合圍完成後守軍戰力 −20%，攻城破壞 +25%。</p><p>有效糧道封鎖：${(g.blockadeRoads||[]).map(id=>locations(g)[id].name).join('、')||'無'}。敵軍靠近會中斷封鎖。</p></article>`;if($('intelContent').innerHTML!==html)$('intelContent').innerHTML=html;
}
function renderMap(){terrain(g);
 if(mapInteraction)return;
 $('gridLayer').style.display=showGrid?'':'none';$('fogLayer').style.display=g.revealed||g.role==='defend'?'none':'';
 $('orderLayer').innerHTML=g.units.filter(u=>u.side===g.role&&u.order?.target&&u.n>0).map(u=>`<path d="M${u.x},${u.y} L${u.order.target.x},${u.order.target.y}" stroke="${u.id===selected?'#d9c383':'#88ab94'}" opacity="${u.id===selected?.8:.3}" stroke-width="1.5" stroke-dasharray="5 5" marker-end="url(#arrow)"/>`).join('');
 $('targetLayer').innerHTML=targets(g).filter(p=>!g.points.some(q=>q.id===p.id)||g.revealed||g.role==='defend'||g.stats.breaches>0||g.units.some(u=>u.side===g.role&&Math.hypot(u.x-p.x,u.y-p.y)<90)).map(p=>{const wall=g.walls.find(w=>w.id===p.id),point=g.points.find(q=>q.id===p.id),sel=$('target').value===p.id;const color=wall?(wall.hp<=0?'#dd9f76':'#bdaf7b'):point?(point.owner===g.role?'#8bb59a':'#c58d72'):'#9caf8b';return `<g class="target" data-target="${p.id}" tabindex="0" role="button" aria-label="選取目標${p.name}" transform="translate(${p.x} ${p.y})"><rect class="target-shape" x="-20" y="-18" width="40" height="32" rx="2" fill="${wall?'#4f5545':'#2a4438'}" stroke="${sel?'#ffe2a3':color}" stroke-width="${sel?3:1.5}"/><text text-anchor="middle" y="5" fill="${color}" font-size="16" font-family="serif">${wall?(wall.hp<=0?'破':'門'):point?'據':p.id==='hill'?'望':p.id==='camp'?'糧':p.id==='bridge'?'橋':'道'}</text><text class="map-text" text-anchor="middle" y="-29">${p.name}</text>${wall?`<rect x="-22" y="21" width="44" height="3" fill="#182a22"/><rect x="-22" y="21" width="${wall.hp*.44}" height="3" fill="${color}"/><text class="map-meta" y="39" text-anchor="middle">${Math.round(wall.hp)}%</text>`:point?`<text class="map-meta" y="32" text-anchor="middle">${point.contested?'交戰 · 無法占領':point.progress>0?Math.round(point.progress)+'%':(g.revealed||g.role==='defend'?'守軍控制':'?')}</text>`:''}${showIntel&&g.intel[p.id]&&g.role==='attack'?`<text class="map-meta" x="32" y="3">約 ${g.intel[p.id].low}–${g.intel[p.id].high}</text>`:''}</g>`;}).join('');
 const geo=geometry(g);if(!geo.noRiver)$('targetLayer').insertAdjacentHTML('beforeend',`${g.level===2&&g.t<480?`<text x="${geo.ford-30}" y="620" class="map-text">洪水 · 08:00 退去</text>`:''}${['bridge','pontoon'].map(id=>`<path d="M${geo[id]} 540 L${geo[id]} 590" stroke="${(g.bridges?.[id]??(id==='bridge'?100:0))>=100?'#c2af7d':'#77877b'}" stroke-width="12" stroke-dasharray="${(g.bridges?.[id]??(id==='bridge'?100:0))>=100?'0':'4 5'}" pointer-events="none"/><text x="${geo[id]+20}" y="550" class="map-meta">${id==='bridge'?'石橋':'浮橋'} ${Math.round(g.bridges?.[id]??(id==='bridge'?100:0))}%</text>`).join('')}`);

 $('convoyLayer').innerHTML=g.convoys.filter(c=>g.role==='attack'||g.units.some(u=>u.side==='defend'&&Math.hypot(u.x-c.x,u.y-c.y)<200)).map(c=>`<g transform="translate(${c.x},${c.y})"><rect width="16" height="10" x="-8" y="-5" fill="#b3a576" stroke="#1b2a23"/><text class="map-meta" y="23" text-anchor="middle">運糧隊</text></g>`).join('');
 const shown=g.units.filter(u=>u.n>0&&visible(g,u)),marks=new Map(shown.map(u=>[u.id,{x:u.x,y:u.y}]));
 $('unitLayer').innerHTML=shown.map(u=>{const ours=u.side===g.role,c=ours?'#93b7a1':'#da927a',sel=u.id===selected;return `<g class="unit-map" data-unit="${u.id}" transform="translate(${u.x.toFixed(1)} ${u.y.toFixed(1)})" tabindex="0" role="button" aria-label="${ours?'選取':'查看敵軍'}${u.name}">${sel?'<circle r="28" fill="none" stroke="#e2c482" stroke-width="1.5" stroke-dasharray="3 3"/>':''}<rect x="-17" y="-13" width="34" height="27" rx="2" fill="${ours?'#294b3d':'#634236'}" stroke="${sel?'#efd499':c}" stroke-width="${sel?2.5:1}"/><text y="6" text-anchor="middle" fill="${c}" font-family="serif" font-size="17">${icons[u.type]}</text><text class="map-meta" text-anchor="middle" y="30">${ours?fmt(u.n):'約 '+Math.max(50,Math.round(u.n/100)*100)}</text>${u.pending.length?'<circle cx="19" cy="-14" r="4" fill="#e0c57c"/>':''}${u.routed?'<text y="-21" text-anchor="middle" class="map-text">潰</text>':''}</g>`;}).join('');
 const tactical=unit().pending[0]||unit().order;if(tactical&&['ambush','intercept'].includes(tactical.action)){const center=tactical.action==='ambush'&&!tactical.sprung?tactical.target:tactical.anchor;if(center)$('orderLayer').insertAdjacentHTML('afterbegin',`<circle cx="${center.x}" cy="${center.y}" r="${tactical.action==='ambush'?90:220}" fill="#b7a45d" fill-opacity=".07" stroke="#d1b572" stroke-dasharray="6 5" pointer-events="none"/>`);}
 const selectedUnit=unit();$('combatLayer').innerHTML=shown.filter(u=>u.engagingId&&(u.id===selected||u.engagingId===selected)).map(u=>{const enemy=shown.find(e=>e.id===u.engagingId);if(!enemy)return '';const from=marks.get(u.id),to=marks.get(enemy.id);return `<path d="M${from.x},${from.y} L${to.x},${to.y}" stroke="${u.id===selected?'#e5c370':'#ea9274'}" stroke-width="2.5" stroke-dasharray="7 4" marker-end="url(#${u.id===selected?'combatOut':'combatIn'})"/><circle cx="${(from.x+to.x)/2}" cy="${(from.y+to.y)/2}" r="4" fill="#edac82"/>`;}).join('');
 const opponent=g.units.find(v=>v.id===selectedUnit.engagingId),incoming=(selectedUnit.underAttackBy||[]).map(id=>knownName(id));const summary=`<strong>${selectedUnit.name} · 即時交戰</strong><span>正在攻擊：${opponent?esc(knownName(opponent.id)):selectedUnit.engagingWallId?g.walls.find(w=>w.id===selectedUnit.engagingWallId)?.name:'無'}</span><span>正遭攻擊：${incoming.length?incoming.map(esc).join('、'):'無'}</span><button id="showCombatBtn">交戰詳情</button>`;if($('combatSummary').innerHTML!==summary)$('combatSummary').innerHTML=summary;

}
function tutorial(){
 const q=ensureGuide(g),list=stepsFor(g.role,g.level,g.mapRevision||0),s=list[q.index];
 const justDone=refreshGuide(g,{selected,tab});
 if(justDone){guideNotice='操作完成，已暫停。按「下一步」繼續。';save(true);}
 $('tutorialLabel').textContent=q.enabled?'軍師 · 逐步教學':'軍師 · 戰場提醒';
 $('tutorialText').textContent=g.alert||(q.enabled?`${q.index+1} / ${list.length} · ${s.title}`:g.role==='attack'?'取得情報、保護補給，破門後仍須占領官署與另一處據點。':'保衛官署，預備隊隨時準備接替疲勞部隊。');
 $('tutorialBtn').textContent=q.enabled?'查看教學 ↓':'開啟教學';
 const panel=$('guidePanel');panel.hidden=!q.enabled;
 const done=q.completed.includes(s.id),read=s.condition.type==='read',waiting=['intel','breach','ended','arrived'].includes(s.condition.type);
 const key=JSON.stringify([q.index,q.enabled,done,g.speed===0,guideNotice]);
 if(key!==guideKey){guideKey=key;panel.innerHTML=`<div class="guide-progress"><i style="width:${q.completed.length/list.length*100}%"></i></div><div class="guide-top"><span class="guide-count">第${g.level||1}關教學 ${q.index+1} / ${list.length}</span><h2>${s.title}</h2><div class="guide-tools"><button data-guide="chapters">教學目錄</button><button data-guide="previous" ${q.index===0?'disabled':''}>上一步</button><button data-guide="skip">略過此步</button><button data-guide="close">收起</button></div></div><div class="guide-body"><div><p>${s.text}</p><p class="guide-tip">${s.tip}</p><span class="guide-status" role="status">${done?'✓ 已完成，可前往下一步':read?'閱讀後按「我明白了」':guideNotice||'等待你完成本步操作'}</span></div><div class="guide-actions">${!done&&!read?`<button data-guide="prepare">${s.setup?'帶我設定':waiting?(g.speed?'暫停時間':'繼續時間 · 4×'):'定位操作區'}</button>`:''}<button data-guide="next" class="primary" ${!done&&!read?'disabled':''}>${q.index===list.length-1?'完成教學':read?'我明白了 · 下一步':'下一步 →'}</button></div></div>`;}
 $$('.guide-focus').forEach(el=>el.classList.remove('guide-focus'));if(q.enabled&&!done&&s.focus)$$(s.focus).forEach(el=>el.classList.add('guide-focus'));
}
function guideChapters(){const q=ensureGuide(g),list=stepsFor(g.role,g.level,g.mapRevision||0);modal(`<span class="eyebrow">第${g.level||1}關 · ${g.role==='attack'?'攻城':'守城'}完整教學</span><h2>從部署到戰後結算</h2><p>可跳至任何章節練習。這只切換教學，不會重開戰局或清除軍令。</p><div class="guide-chapters">${list.map((s,i)=>`<button class="guide-chapter ${i===q.index?'current':''}" data-guide-jump="${i}"><span>${q.completed.includes(s.id)?'✓ 完成':q.skipped.includes(s.id)?'已略過':String(i+1).padStart(2,'0')}</span>${s.title}</button>`).join('')}</div><div class="modal-buttons"><button data-guide="resume" class="primary">繼續教學</button><button data-guide="restart">從第一步重看</button><button data-close>返回戰場</button></div>`);}
function guidePrepare(){const s=stepsFor(g.role,g.level,g.mapRevision||0)[ensureGuide(g).index];guideNotice='';if(s.setup){const z=s.setup;g.speed=0;select(z.unit);$('action').value=z.action;options();$('target').value=z.target;if(z.formation)$('formation').value=z.formation;if(z.equipment)$('equipment').value=z.equipment;render();if(z.plan){plan();$('trigger').value='engaged';$('triggerUnit').value='a3';$('wait').value='30';}else{$('sendBtn').scrollIntoView({block:'center',behavior:'smooth'});$('sendBtn').focus({preventScroll:true});toast('欄位已設定，請親自按「傳達軍令」。');}return;}
 if(['intel','breach','ended','arrived'].includes(s.condition.type)){setSpeed(g.speed?0:4);return;}
 const el=document.querySelector(s.focus);if(el){el.scrollIntoView({block:'center',behavior:'smooth'});if(el.matches('button,select'))el.focus({preventScroll:true});}toast(s.condition.type==='select'?'請點選金色外框標示的部隊。':'請點選右側「敵情」分頁。');}
function guideAction(action){const q=ensureGuide(g),list=stepsFor(g.role,g.level,g.mapRevision||0);guideNotice='';if(action==='prepare'){guidePrepare();return;}if(action==='chapters'){guideChapters();return;}if(action==='next'){nextStep(g);}if(action==='previous'){q.index=Math.max(0,q.index-1);g.speed=0;}if(action==='skip'){if(!q.skipped.includes(list[q.index].id))q.skipped.push(list[q.index].id);if(q.index<list.length-1)q.index++;else q.enabled=false;g.speed=0;}if(action==='freeplay'){q.enabled=false;closeModal();}if(action==='close'){q.enabled=false;toast('已收起教學，進度保留。可由右上「教學」繼續。');}if(action==='resume'){q.enabled=true;closeModal();g.speed=0;}if(action==='restart'){q.index=0;q.enabled=true;closeModal();g.speed=0;}guideKey='';render();save(true);if(['resume','restart'].includes(action))$('guidePanel').scrollIntoView({block:'center',behavior:'smooth'});}

function render(){
 g.difficulty??=g.role==='defend'?'recruit':'standard';const signature=choicesSignature();if(signature!==targetSignature&&!['target','ambushEnemy'].includes(document.activeElement?.id))options();$('ambushEnemyLabel').hidden=$('action').value!=='ambush';$('reportBtn').hidden=!g.ended;
 roster();const u=unit();$('selectedName').textContent=u.name;$('selectedGeneral').textContent=`${u.general} · ${u.trait} · 統率 ${u.type==='heavy'?'★★★★☆':'★★★☆☆'}`;$('selectedState').textContent=`${u.status} · 士氣 ${Math.round(u.morale)}% · 疲勞 ${Math.round(u.fatigue)}% · 陣型完整 ${Math.round(u.cohesion??100)}%`;$('equipmentLabel').hidden=u.type!=='engineer';$('sendBtn').disabled=u.routed||u.n<=0||!!g.ended||(!automaticOrders.includes($('action').value)&&!choices().some(p=>p.id===$('target').value));$('planBtn').disabled=$('sendBtn').disabled;
 $('roleName').textContent=(g.role==='attack'?'攻城方':'守城方')+(g.role==='defend'?' · '+(g.difficulty==='recruit'?'新兵':'標準'):' · 主帥');$('supply').textContent=Math.round(g.supplies[g.role]);$('supplyState').textContent=g.role==='attack'?`有效封鎖 ${g.blockadedGates??0} / 4 門`:g.supplies[g.role]>35?'供應穩定':'補給短缺';const enemy=g.supplies[g.role==='attack'?'defend':'attack'];$('enemySupply').textContent=enemy>65?'充足':enemy>25?'消耗中':'匱乏';$('weather').textContent=({晴:'☀',雨:'☂',霧:'≋'}[g.weather])+' '+g.weather;$('day').textContent=g.night?'第一日 · 夜間':'第一日 · 日間';$('clock').textContent=clock(g.t);$('deadline').textContent=clock(Math.max(0,2700-g.t));
 $$('[data-speed]').forEach(b=>b.classList.toggle('active',Number(b.dataset.speed)===g.speed));$('pauseLabel').style.display=g.speed===0?'':'none';$('officeState').textContent=g.points.find(p=>p.id==='office').owner==='attack'?'攻軍':'守軍';$('pointCount').textContent=g.points.filter(p=>p.owner==='attack').length+' / 4';$('missionTitle').textContent=(g.role==='attack'?'攻取':'守住')+(g.city||'青石城');$('missionText').textContent=g.role==='attack'?'占領官署與另一處據點，或切斷補給迫使守軍投降。':'拖至援軍抵達，或擊潰攻軍。官署與另一處要地同時失守即告敗。';$('surrenderBtn').textContent=g.role==='attack'?'派遣使者勸降 ↗':'開城投降';
 document.querySelector('.battle-name b').textContent=(g.city||'青石城')+'之戰';document.querySelector('.brand small').textContent='中軍指揮所 · 第'+(g.level||1)+'章';document.querySelector('.map-head b').textContent=(g.city||'青石城')+'及周邊';document.querySelector('.fog-label').textContent=g.city||'青石城';$('map').setAttribute('aria-label',(g.city||'青石城')+'戰術地圖');document.title='兵臨城下｜'+(g.city||'青石城');if(g.level===2)$('missionText').textContent=(g.role==='attack'?'占領官署與糧倉，或斷糧迫降。':'守住官署與糧倉，等待 45:00 援軍。')+(g.t<480?'淺灘 08:00 退水。':'淺灘已通行。')+(g.northSupplyOpen===false?'北門補糧已中斷。':'北門糧道仍開放。');
 if(g.level===3)$('missionText').textContent=(g.role==='attack'?'封鎖三門取得合圍優勢，攻下官署與內城兵營，或迫降。':'保住官署與內城兵營，打斷封鎖並守至 45:00。')+'合圍進度 '+Math.floor(g.isolation||0)+' / 120 秒。';
 $('delayPreview').textContent=`傳令預估 ${Math.round(Math.max(5,Math.min(30,5+Math.hypot(u.x-(g.role==='attack'?locations(g).camp.x:locations(g).office.x),u.y-(g.role==='attack'?locations(g).camp.y:locations(g).office.y))/26+(u.fatigue>60?5:0))))} 秒`;
 $('spyBtn').disabled=g.spy>0||g.spyCooldown>g.t||!!g.ended;$('spyBtn').innerHTML=g.spy>0?`密探回報倒數 ${Math.ceil(g.spy)} 秒`:g.spyCooldown>g.t?`密探休整 ${Math.ceil(g.spyCooldown-g.t)} 秒`:'派遣密探 <small>−3 補給</small>';
 renderIntel();renderMap();tutorial();if(g.ended&&!endedShown){endedShown=true;save(true);record();result();}
}
function modal(html){$('modal').classList.remove('dialogue-modal');g.speed=0;$('modalContent').innerHTML=html;if(!$('modal').open)$('modal').showModal();render();}
function closeModal(){$('modal').classList.remove('dialogue-modal');$('modal').close();}
function record(){try{const history=JSON.parse(localStorage.getItem('siege-campaign-v1')||'[]');history.unshift({...g.ended,role:g.role,date:new Date().toISOString(),generals:own().filter(u=>u.n>0).map(u=>u.general)});localStorage.setItem('siege-campaign-v1',JSON.stringify(history.slice(0,20)));}catch{}}
function result(){if(!g.ended)return;const r=g.ended,report=r.report?.units?r.report:battleReport(g);r.report=report;const mine=report[g.role];const rows=[['出征兵力','initial'],['殺敵','kills'],['戰損合計','losses'],['其中：戰死','dead'],['其中：傷兵','wounded'],['剩餘可作戰兵力','survivors']];modal(`<span class="eyebrow">${g.city||'青石城'}之戰 · 雙方結算</span><h2>${r.result==='victory'?'大捷 · 戰役勝利':'戰役結束 · 收攏餘部'}</h2><p>${esc(r.reason)} 用時 ${clock(r.time)}。</p><div class="result-grid"><div><b>${fmt(mine.kills)}</b><span>我軍殺敵</span></div><div><b>${fmt(mine.losses)}</b><span>我軍戰損</span></div><div><b>${fmt(mine.survivors)}</b><span>剩餘可作戰</span></div></div><table class="battle-report"><caption>雙方兵力與戰損對照 · 單位：人</caption><thead><tr><th scope="col">統計項目</th><th scope="col" class="${g.role==='attack'?'report-own':''}">攻城方${g.role==='attack'?' · 我軍':' · 敵軍'}</th><th scope="col" class="${g.role==='defend'?'report-own':''}">守城方${g.role==='defend'?' · 我軍':' · 敵軍'}</th></tr></thead><tbody>${rows.map(([name,key])=>`<tr class="${['kills','losses'].includes(key)?'report-main':''}"><th scope="row">${name}</th><td class="${g.role==='attack'?'report-own':''}">${fmt(report.attack[key])}</td><td class="${g.role==='defend'?'report-own':''}">${fmt(report.defend[key])}</td></tr>`).join('')}</tbody></table><p class="report-note">殺敵＝對方戰死人數；戰損＝戰死＋傷兵。剩餘兵力包含潰退後仍存活的士兵，投降部隊不計入殺敵。</p>${unitResults(report)}<p>存活將領：${own().filter(u=>u.n>0).map(u=>u.general).join('、')||'無'}。戰報與戰局存檔保留於此瀏覽器。</p><div class="modal-buttons"><button class="primary" data-new="${g.role}">重新挑戰</button><button data-new="${g.role==='attack'?'defend':'attack'}">改以${g.role==='attack'?'守城':'攻城'}方出戰</button>${g.level!==3?`<button data-new="attack" data-level="${(g.level||1)+1}">挑戰下一關</button>`:''}<button data-close>檢視戰場</button></div>`);save(true);}

function unitResults(report){const value=v=>v==null?'—':fmt(v);return `<h3>逐營戰果</h3><p class="report-note">輸出＝實際造成敵軍傷亡；承傷＝本營戰死＋傷兵（人），並非減免前傷害。攻城＝削減城防百分點；毀糧＝削減物資耐久。殺敵已包含在輸出內。</p>${['attack','defend'].map(side=>`<div class="unit-report-scroll" tabindex="0" aria-label="${side==='attack'?'攻城':'守城'}逐營戰果，可左右捲動"><table class="battle-report unit-report"><caption>${side==='attack'?'攻城方':'守城方'}${side===g.role?' · 我軍':' · 敵軍'}</caption><thead><tr>${['部隊','殺敵','輸出','承傷','剩餘','攻城','毀糧','伏擊次數'].map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${report.units[side].map(u=>`<tr><th scope="row">${esc(u.name)}${u.partial?'＊':''}</th><td>${value(u.kills)}</td><td>${value(u.inflicted)}</td><td>${value(u.taken)}</td><td>${value(u.survivors)}</td><td>${u.wallDamage??'—'}</td><td>${u.materialDamage??'—'}</td><td>${value(u.ambushes)}</td></tr>`).join('')}</tbody></table></div>`).join('')}${Object.values(report.units).flat().some(u=>u.partial)?'<p class="report-note">＊舊存檔未記錄先前的逐營輸出，僅顯示更新後可追溯的戰果；— 表示無紀錄。承傷及剩餘仍為整場數值。重新開戰可獲得完整統計。</p>':''}`;}
function help(){modal(`<span class="eyebrow">中軍兵法 · 操作指南</span><h2>運籌帷幄，審勢而動</h2><div class="help-grid"><section><h3>掩護工程營</h3><p>先選護衛部隊，軍令選「掩護友軍」，在目標的友軍分組選工程營，再傳令。護衛會跟隨、迎擊目標附近敵軍，距離過遠便回到友軍身邊。可用槍兵近身護衛、弓兵遠程支援，兩營同時掩護一營。</p><p>掩護不是無敵護盾；敵軍逼近施工位置仍會停工，需由護衛清除威脅。工程營移動後護衛會跟隨，不必反覆點地圖。</p></section><section><h3>兵種與條件克制</h3><p>槍兵：士氣高於 55、疲勞低於 45 且未潰退時，敵騎兵對其傷害降為 45%。騎兵：對疲勞高於 65 或潰退部隊傷害 ×1.6；衝鋒增加傷害與疲勞。重步適合近戰與城下作戰；輕步行軍快，適合偵察和增援。沒有單純兵種必勝。</p><p>弓兵怕近戰，雨中效率降低。盾陣減少箭傷但走得慢；疏散陣減少箭傷卻削弱近戰；密集陣近戰更強但承受更多箭傷。士氣、疲勞、陣型和補給共同決定戰力。</p></section><section><h3>架橋與拆橋</h3><p>攻方選工程營 → 架橋／修橋 → 石橋或浮橋施工點 → 傳令。抵達岸邊後施工，完整工程約 100 秒、消耗 10 補給。守方選步兵 → 拆橋 → 選橋 → 傳令，完整部隊約 80 秒拆除。兵力減少會延長工期，近處有敵軍時停工。</p><p>橋梁耐久滿 100% 才能通行。浮橋在石橋東側；斷橋後可繞東方淺灘，橋上部隊先撤至岸邊。右側敵情可查看施工進度。</p></section><section><h3>01 選兵與傳令</h3><p>點左側軍營或地圖軍旗，選軍令及目標，再按「傳達軍令」。軍令需 5–30 秒抵達。空白鍵暫停，數字 1／2／4 切換倍速。地圖空白處可指定行軍位置。</p></section><section><h3>02 情報與欺敵</h3><p>敵軍顯示估測人數；城內未知。派輕步營到北嶺或東門偵察，抵達後觀察 18 秒；密探需 60 秒。情報越舊，可信度越低。</p></section><section><h3>03 攻城與器械</h3><p>工程營可選投石機、攻城槌、雲梯、井闌及盾車。投石機遠程破牆，槌近距離破門；雲梯在城下架設 35 秒後協助附近步兵登城。井闌壓制守軍；盾車減輕附近友軍箭傷。</p></section><section><h3>04 協同與自主</h3><p>「安排協同計畫」可設定：前令完成、時間延後、友軍抵達或交戰後。新傳軍令會取代原計畫。保守僅近身自衛，標準就近作戰，積極可短距離迎擊。玩家守軍不會自動出城；要出擊請指定敵軍攻擊或行軍到城外。電腦守軍評估附近可見敵我兵力、支援與自身狀態才出擊。</p></section><section><h3>05 士氣與陣型</h3><p>傷亡、缺糧使士氣降低；低於門檻即潰退，撤回重整。盾陣抗箭但慢，密集陣近戰強但怕箭，疏散陣相反；衝鋒更快但容易疲勞。騎兵打擊疲憊敵人較有效。</p></section><section><h3>06 補給與圍城</h3><p>攻軍運糧隊每 160 秒從後方送糧。守軍能出城截擊或火攻糧營。每門需至少 250 名未潰退士兵完成封鎖；附近有超過 150 名出城守軍時，封鎖暫停。用預備隊指定攔截、保護封鎖部隊。缺糧會降低守軍戰力與伏擊效果，補給低於 18 時可勸降。</p></section><section><h3>07 破門後的目標</h3><p>步兵必須先清除據點附近守軍，才能占領。破口限制近戰展開，城內有糧的守軍享有據點掩護；先圍城、偵察伏兵，再輪換主力突入。攻軍須控制官署與另一據點；雲梯可讓步兵提前登城。守軍撐至 45:00 援軍抵達即可獲勝。</p></section><section><h3>08 時間、天候與存檔</h3><p>有戰鬥時 20× 自動停止。重大事件自動暫停。5 分鐘後降雨，10 分鐘起霧，15 分鐘放晴，20–30 分鐘入夜。每 30 秒自動存檔，也可手動存檔。</p></section><section><h3>09 指定敵軍與交戰辨識</h3><p>先選己方部隊，再點敵軍軍旗，或在目標選單選可見敵軍。可指定攻擊、攔截，再傳令。右側「交戰」與地圖下方會顯示攻擊誰、被誰攻擊；重疊時從部隊清單逐一選取。</p></section><section><h3>10 攔截與埋伏</h3><p>攔截會估計可見敵軍前進方向，只在標示的攔截範圍內追擊；失去視野只搜索最後位置。埋伏須先選地點，可指定一支敵軍或任意敵軍；抵達並準備 10 秒，敵軍進入伏擊圈且可交戰時觸發，未被識破且補給高於 35 時，突襲造成額外傷亡、士氣與陣型打擊，敵軍戰力暫降 50 秒。斥候近距離偵察、晴天北嶺觀察或密探可揭露伏兵 180 秒，消除突襲加成。</p></section><section><h3>11 守城新兵模式</h3><p>守城預設新兵難度：敵軍分批進攻、攻城火力較低，占領較慢。城牆提供掩護，城外部隊不能占領城內據點。先集中兩隊弓兵到南城射位，讓西城守備保護市集，再考慮出城。可在選單切換標準難度。</p></section></div><div class="modal-buttons"><button class="primary" data-close>回到中軍</button></div>`);}
function menu(){let history=[];try{history=JSON.parse(localStorage.getItem('siege-campaign-v1')||'[]');}catch{}modal(`<span class="eyebrow">戰局管理</span><h2>${g.city||'青石城'}之戰</h2><p>本關支援攻守雙方。另開戰局會覆蓋目前存檔，戰後紀錄保留。</p><div class="modal-buttons"><button class="primary" data-close>返回戰場</button><button id="loadBtn">讀取存檔</button><button id="restartBtn">另開戰局</button><button id="withdrawBtn">${g.role==='attack'?'撤軍':'投降'}並結算</button></div>${g.role==='defend'?`<h3 style="margin-top:24px;font-size:17px">守城難度 · ${g.difficulty==='standard'?'標準':'新兵'}</h3><p>新兵：攻軍分批部署，攻城火力較低，據點占領較慢，守軍士氣較穩定。切換即生效，不會恢復損失的兵力或城防。</p><div class="modal-buttons"><button data-difficulty="recruit">新兵 · 教學建議</button><button data-difficulty="standard">標準</button></div>`:''}<h3 style="margin-top:28px;font-size:17px">戰役紀錄</h3>${history.length?history.slice(0,5).map(h=>`<div class="log">${h.role==='attack'?'攻城':'守城'} · ${h.result==='victory'?'勝利':'敗退'} · ${clock(h.time)} · 餘部 ${fmt(h.survivors)} 人</div>`).join(''):'<p>尚無戰後紀錄。完成第一場戰役後，將在這裡保存將領與兵力結算。</p>'}`);}
function plan(){const u=unit();modal(`<span class="eyebrow">${u.name} · 協同軍令</span><h2>安排下一步行動</h2><p>將目前設定的「${ORDERS[$('action').value]} · ${$('target').selectedOptions[0]?.textContent}」加入計畫。觸發後仍需傳令時間。</p><div class="plan-form"><label>觸發條件<select id="trigger"><option value="now">本營前一命令完成</option><option value="time">本營目前命令開始後</option><option value="engaged">指定友軍開始交戰後</option><option value="arrived">指定友軍抵達目標後</option></select></label><label>協同部隊<select id="triggerUnit">${own().filter(v=>v.id!==selected).map(v=>`<option value="${v.id}">${v.name}</option>`).join('')}</select></label><label>延後秒數<input id="wait" type="number" value="30" min="0" max="300" step="5"></label></div><p class="modal-warning">例如：弓兵開始交戰 30 秒後，第一重步營向南門推進。工程营可設定在重步營抵達後架梯。</p><div class="modal-buttons"><button id="confirmPlan" class="primary">加入協同計畫</button><button data-close>取消</button></div>`);}
function start(role,level=g.level||1){g=newGame(role,level);selected=role==='attack'?'a1':'d1';endedShown=false;mapPick=null;guideKey='';guideNotice='';ensureGuide(g);options();closeModal();select(selected);save(true);toast('已部署完成，暫停中。');showStory();}
function newMenu(){modal(`<span class="eyebrow">選擇戰役 · 將覆蓋目前戰局</span><h2>兵臨城下</h2><p>${esc(PROLOGUE)}</p><h3>第一關 · 青石城之戰</h3><p class="story-summary">${esc(storyFor(1).summary)}</p><p>學習偵察、傳令與攻城。占領官署與另一據點，或圍城迫降。</p><div class="modal-buttons"><button data-new="attack" data-level="1">攻方 · 4,800 人</button><button data-new="defend" data-level="1">守方 · 2,600 人</button></div><h3>第二關 · 臨川渡河戰</h3><p class="story-summary">${esc(storyFor(2).summary)}</p><p>城池位於東北，西側石橋、東側浮橋與西端淺灘通往不同戰線。淺灘於 08:00 退水；兩支工兵可分路架橋，護衛營可跟隨掩護；勝利須奪下官署與糧倉，或迫降。雙方獨立編制，不繼承第一關傷亡。</p><div class="modal-buttons"><button class="primary" data-new="attack" data-level="2">攻方 · 10 營／6,800 人</button><button data-new="defend" data-level="2">守方 · 7 營／3,600 人</button><button data-close>取消</button></div><h3>第三關 · 朔風合圍戰</h3><p class="story-summary">${esc(storyFor(3).summary)}</p><p>全新陸路要塞：四條糧道、狹長城池、東側集結。封鎖可截糧與休整，三門合圍 120 秒可削弱守軍、提高攻城效率。奪取官署與內城兵營，或迫降。</p><div class="modal-buttons"><button data-new="attack" data-level="3" class="primary">攻方 · 10 營／7,600 人</button><button data-new="defend" data-level="3">守方 · 7 營／4,200 人</button></div>`);}

$('roster').addEventListener('click',e=>{const b=e.target.closest('[data-unit]');if(b)select(b.dataset.unit);});
$('map').addEventListener('pointerdown',()=>{mapInteraction=true;});$('roster').addEventListener('pointerdown',()=>{mapInteraction=true;});window.addEventListener('pointerup',()=>setTimeout(()=>{mapInteraction=false;},80));window.addEventListener('pointercancel',()=>{mapInteraction=false;});
$('map').addEventListener('click',e=>{const ub=e.target.closest('[data-unit]');if(ub){const shown=g.units.filter(u=>u.n>0&&visible(g,u)),u=shown.find(u=>u.id===ub.dataset.unit);if(!u)return;if($('action').value==='escort'&&u.side===g.role&&u.id!==selected){options();$('target').value=u.id;render();toast('已選掩護 '+u.name+'，請傳達軍令。');return;}const cluster=nearbyUnits(shown,u.id);if(cluster.length>1)unitPicker(cluster);else if(u.side===g.role)select(u.id);else unitPicker([u]);return;}const t=e.target.closest('[data-target]');if(t){if(!choices().some(p=>p.id===t.dataset.target)){toast(targetHint($('action').value));return;}$('target').value=t.dataset.target;renderMap();$('mapHint').textContent=`已選取${targets(g).find(p=>p.id===t.dataset.target).name} · 按下方「傳達軍令」`;return;}const pt=$('map').createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const p=pt.matrixTransform($('map').getScreenCTM().inverse());mapPick={x:Math.max(20,Math.min(980,p.x)),y:Math.max(20,Math.min(800,p.y)),name:'指定位置'};if(!['ambush','scout'].includes($('action').value))$('action').value='move';options();$('target').value='custom';$('mapHint').textContent=$('action').value==='ambush'?'已指定伏擊地點 · 按下方「傳達軍令」':'已指定行軍位置 · 按下方「傳達軍令」';render();});
$('map').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
$$('[data-speed]').forEach(b=>b.onclick=()=>setSpeed(Number(b.dataset.speed)));
function setSpeed(s){if(g.ended){toast('戰役已結束，可在選單另開戰局。');return;}if(s===20&&g.units.some(u=>u.engagingId||u.engagingWallId)){toast('部隊正在交戰，請使用 1×、2× 或 4×。');return;}g.speed=s;if(s)g.lastSpeed=s;g.alert=null;render();}
$$('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;$$('[data-tab]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-selected',String(x===b));});renderIntel();});
$('intelContent').onclick=e=>{const pick=e.target.closest('[data-combat-select]');if(pick){select(pick.dataset.combatSelect);return;}const b=e.target.closest('[data-cancel]');if(b){const [id,i]=b.dataset.cancel.split(':');g.units.find(u=>u.id===id).plan.splice(Number(i),1);renderIntel();}};
$('target').onchange=()=>{const p=commandTargets(g).find(p=>p.id===$('target').value);if(p?.allyId)$('action').value='escort';if(p?.unitId&&!['attack','intercept'].includes($('action').value))$('action').value='attack';render();};$('action').onchange=()=>{options();render();};$('sendBtn').onclick=()=>send();$('planBtn').onclick=plan;$('saveBtn').onclick=()=>save();$('reportBtn').onclick=result;$('helpBtn').onclick=help;$('settingsBtn').onclick=menu;$('closeModal').onclick=closeModal;
$('unitsBtn').onclick=()=>unitPicker(g.units.filter(u=>u.n>0&&visible(g,u)));$('combatSummary').onclick=e=>{if(e.target.closest('#showCombatBtn')){tab='combat';$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));renderIntel();$('intelContent').scrollIntoView({block:'center',behavior:'smooth'});}};
$('gridBtn').onclick=()=>{showGrid=!showGrid;$('gridBtn').classList.toggle('active',showGrid);renderMap();};$('intelBtn').onclick=()=>{showIntel=!showIntel;$('intelBtn').classList.toggle('active',showIntel);renderMap();};$('centerBtn').onclick=()=>{$('map').setAttribute('viewBox','0 0 1000 820');toast('目前顯示完整戰場');};$('spyBtn').onclick=()=>{if(spy(g))toast('密探已派出');render();};
$('surrenderBtn').onclick=()=>{if(g.role==='attack'){surrender(g);render();toast(g.ended?'守軍接受勸降':'守軍拒絕勸降，繼續削弱糧秣或士氣。');}else modal('<h2>開城投降？</h2><p>本戰將以失敗結算，保存目前尚存的部隊。</p><div class="modal-buttons"><button id="confirmWithdraw" class="primary">確認投降</button><button data-close>繼續守城</button></div>');};
$('tutorialBtn').onclick=()=>{ensureGuide(g).enabled=true;g.speed=0;render();$('guidePanel').scrollIntoView({block:'center',behavior:'smooth'});};
$('guideBtn').onclick=guideChapters;
$('guidePanel').onclick=e=>{const b=e.target.closest('[data-guide]');if(b)guideAction(b.dataset.guide);};

$('modalContent').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.dialogue){dialogueAction(b.dataset.dialogue);return;}if(b.dataset.pickAlly){select(b.dataset.pickAlly);closeModal();return;}if(b.dataset.foe){stageEnemy(b.dataset.foe,b.dataset.tactic);return;}if(b.dataset.difficulty){g.difficulty=b.dataset.difficulty;save(true);menu();return;}if(b.dataset.guide){guideAction(b.dataset.guide);return;}if(b.dataset.guideJump!==undefined){const q=ensureGuide(g);q.index=Number(b.dataset.guideJump);q.enabled=true;g.speed=0;guideNotice='';guideKey='';closeModal();render();save(true);$('guidePanel').scrollIntoView({block:'center',behavior:'smooth'});return;}if(b.hasAttribute('data-close'))closeModal();if(b.dataset.new)start(b.dataset.new,Number(b.dataset.level)||g.level||1);if(b.id==='confirmPlan'){const wait=Math.max(0,Math.min(300,Number($('wait').value)||0));send(true,{trigger:$('trigger').value,triggerUnit:$('triggerUnit').value,wait});closeModal();}if(b.id==='restartBtn')newMenu();if(b.id==='loadBtn'){try{const s=JSON.parse(localStorage.getItem('siege-qingshi-v1'));if(!valid(s))throw Error();g=s;g.speed=0;selected=own()[0].id;endedShown=!!g.ended;closeModal();options();select(selected);toast('已讀取存檔，時間暫停。');}catch{toast('沒有可讀取的有效存檔。');}}if(b.id==='withdrawBtn')modal('<h2>撤離戰場？</h2><p>這將立即結束戰役，以敗退結算傷亡。</p><div class="modal-buttons"><button id="confirmWithdraw" class="primary">確認結束戰役</button><button data-close>繼續指揮</button></div>');if(b.id==='confirmWithdraw'){closeModal();g.role==='attack'?withdraw(g):surrender(g);render();}};
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName)||$('modal').open)return;if(e.code==='Space'){e.preventDefault();setSpeed(g.speed?0:g.lastSpeed);}if(['1','2','4'].includes(e.key))setSpeed(Number(e.key));if(e.key.toLowerCase()==='s'){e.preventDefault();save();}});
function valid(s){return s?.version===1&&Array.isArray(s.units)&&[11,17].includes(s.units.length)&&s.supplies&&s.intel&&s.points&&['attack','defend'].includes(s.role)&&Number.isFinite(s.t);}
let stored=null;try{stored=JSON.parse(localStorage.getItem('siege-qingshi-v1'));}catch{}if(valid(stored)){g=stored;g.speed=0;selected=own()[0].id;endedShown=!!g.ended;}
const firstGuideVisit=!g.guide;
options();select(selected);
if(firstGuideVisit&&!g.ended)modal(`<span class="eyebrow">${g.city||'青石城'}之戰 · 新手教學</span><h2>讓軍師陪你打一場</h2><p class="story-summary">${esc(storyFor(g.level).summary)}</p><p>從選兵、偵察與傳令開始，逐步練習協同、護糧、休整，再到破門占領。每一步都有明確目標與完成提示。</p><p class="guide-notice">接續目前戰局，不會重開或清除軍令。教學可隨時收起，也可從右上「教學」繼續。</p><div class="modal-buttons"><button data-guide="resume" class="primary">開始逐步教學</button><button data-guide="freeplay">先自由指揮</button></div>`);
let last=performance.now(),acc=0;function loop(now){const real=Math.min(.25,(now-last)/1000);last=now;if(g.speed&&!g.ended&&!$('modal').open){acc+=real*g.speed;let count=0;while(acc>=.25&&g.speed>0&&count<24){tick(g,.25);acc-=.25;count++;}if(g.speed===0)acc=0;}if(now-lastPaint>250){render();lastPaint=now;}if(now-lastSave>30000){save(true);lastSave=now;}requestAnimationFrame(loop);}requestAnimationFrame(loop);
window.addEventListener('beforeunload',()=>save(true));
// Optional browser tools use exactly the same orders and time controls as the UI.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register({name:'read_battle_state',description:'Read the current visible battle state, friendly units, estimates, and objectives without revealing hidden enemies.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({role:g.role,time:g.t,speed:g.speed,units:own().map(u=>({id:u.id,name:u.name,strength:Math.round(u.n),morale:Math.round(u.morale),fatigue:Math.round(u.fatigue),status:u.status,attacking:u.engagingId?knownName(u.engagingId):null,underAttackBy:(u.underAttackBy||[]).map(knownName)})),intel:g.role==='attack'?g.intel:undefined,objectives:g.points.map(p=>({id:p.id,owner:p.owner})),result:g.ended})});
 register({name:'issue_battle_order',description:'Send an order to one friendly unit. Delivery takes simulation time; this replaces that unit’s pending orders and plan.',inputSchema:{type:'object',properties:{unitId:{type:'string'},action:{type:'string',enum:Object.keys(ORDERS)},targetId:{type:'string'}},required:['unitId','action','targetId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!own().some(u=>u.id===input.unitId)||!Object.keys(ORDERS).includes(input.action)||!commandTargets(g).some(p=>p.id===input.targetId))throw Error('Invalid unit, action, or target');if(!issue(g,input.unitId,input.action,input.targetId))throw Error('Unit cannot accept this order');render();return {sent:true,unitId:input.unitId,deliveryTime:g.units.find(u=>u.id===input.unitId).pending[0].eta};}});
 register({name:'set_battle_speed',description:'Pause or resume the simulation at an available speed. High speed is blocked while units are engaged.',inputSchema:{type:'object',properties:{speed:{type:'number',enum:[0,1,2,4,20]}},required:['speed'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||![0,1,2,4,20].includes(input.speed))throw Error('Invalid speed');setSpeed(input.speed);return {speed:g.speed};}});
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}

function knownName(id){const u=g.units.find(v=>v.id===id);return u&&(u.side===g.role||visible(g,u))?u.name:'未確認敵軍';}
function combatReport(){return `<p class="combat-note">交戰狀態即時更新。金線：所選部隊正在攻擊的敵人；紅線：正在攻擊所選部隊的敵人。只顯示視野內連線，虛線路徑代表軍令。</p>`+own().map(u=>`<article class="intel-card"><div class="intel-title"><h3>${u.name}</h3><small>即時狀態</small><button data-combat-select="${u.id}">選取</button></div><p class="combat-line">正在攻擊：${u.engagingId?esc(knownName(u.engagingId)):u.engagingWallId?g.walls.find(w=>w.id===u.engagingWallId)?.name:'無'}</p><p class="combat-line">正遭攻擊：${(u.underAttackBy||[]).length?u.underAttackBy.map(knownName).map(esc).join('、'):'無'}</p><p class="combat-line">${u.status} · 指定目標：${u.order?.enemyId?esc(u.order.target?.name||'指定敵軍'):'未指定敵軍'}</p></article>`).join('');}
function unitPicker(units){modal(`<span class="eyebrow">戰場部隊辨識 · 已暫停</span><h2>${units.length>1?'此處部隊清單':'敵軍詳情'}</h2><p>目前指揮：${unit().name}。軍旗直接標在部隊位置；清單列出相鄰與重疊的部隊，可逐一選取。</p><div class="contact-list">${units.map(u=>`<article class="contact-card ${u.side===g.role?'friendly-card':'enemy-card'}"><strong>${u.side===g.role?'友軍':'敵軍'} · ${u.name}</strong><span>${u.side===g.role?fmt(u.n):'約 '+Math.max(50,Math.round(u.n/100)*100)} 人 · ${u.side===g.role?u.status:u.engagingId?'接戰中':'已目視'}</span>${u.side===g.role?`<small>攻擊：${u.engagingId?esc(knownName(u.engagingId)):'無'}；受擊：${(u.underAttackBy||[]).map(knownName).map(esc).join('、')||'無'}</small><button data-pick-ally="${u.id}">選取這支部隊</button>`:`<div class="contact-actions"><button data-foe="${u.id}" data-tactic="attack">指定攻擊</button><button data-foe="${u.id}" data-tactic="intercept">攔截這支敵軍</button><button data-foe="${u.id}" data-tactic="ambush">設為伏擊對象</button></div>`}</article>`).join('')}</div><p>指定後仍須按「傳達軍令」。目標失去視野時，只會搜索最後確認位置，不會追蹤未知動向。</p>`);}
function stageEnemy(id,tactic){const foe=g.units.find(u=>u.id===id);if(!foe||!visible(g,foe)){toast('敵軍已失去視野，請重新偵察。');return;}$('action').value=tactic;options();if(tactic==='ambush'){$('target').value='custom';mapPick={x:unit().x,y:unit().y,name:'目前伏擊位置'};options();$('target').value='custom';$('ambushEnemy').value=id;}else $('target').value=id;closeModal();render();$('sendBtn').scrollIntoView({block:'center',behavior:'smooth'});toast(tactic==='ambush'?'已指定伏擊對象，可點地圖改伏擊位置，再傳令。':'已指定敵軍，請按「傳達軍令」。');}

$('campaignBtn').onclick=newMenu;

let dialogueIndex=0;
function showStory(){dialogueIndex=0;drawDialogue();}
function drawDialogue(){modal(dialogueHTML(g.level||1,g.role,dialogueIndex));$('modal').classList.add('dialogue-modal');$('modal').scrollTop=0;$('modalContent').querySelector('[data-dialogue="next"]').focus({preventScroll:true});}
function dialogueAction(action){if(action==='skip'||action==='next'&&dialogueIndex>=dialogueFor(g.level,g.role).length-1){closeModal();return;}dialogueIndex=Math.max(0,dialogueIndex+(action==='prev'?-1:1));drawDialogue();}
window.addEventListener('keydown',e=>{if(!$('modal').open||!$('modal').classList.contains('dialogue-modal'))return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();dialogueAction(e.key==='ArrowRight'?'next':'prev');}});
$('modal').addEventListener('close',()=>{$('modal').classList.remove('dialogue-modal');});
$('storyBtn').onclick=showStory;
