import {addOpeningStory} from './stories.mjs';
import {ensureTelemetry,attributeLoss,unitReport} from './telemetry.mjs';
import {geometry,cityInside,moveAlongRoute,portalPoints,legalSegment,findRoute} from './navigation.mjs';
export const LOCS={south:{name:'南門',x:495,y:465},east:{name:'東門',x:690,y:315},west:{name:'西門',x:300,y:315},north:{name:'北門',x:495,y:165},hill:{name:'北嶺觀察點',x:765,y:100},camp:{name:'糧營',x:460,y:735},barracks:{name:'兵營',x:485,y:230},market:{name:'市集',x:440,y:325},grain:{name:'糧倉',x:585,y:325},office:{name:'官署',x:495,y:410},southwatch:{name:'南城東射位',x:550,y:425},westwatch:{name:'南城西射位',x:425,y:425},bridge:{name:'石橋',x:495,y:568},road:{name:'後方道路',x:620,y:775}};
export const TYPES={heavy:{name:'重步',speed:13,power:1.25,range:24},spear:{name:'槍兵',speed:14,power:1.1,range:25},bow:{name:'弓兵',speed:15,power:.72,range:140},light:{name:'輕步',speed:20,power:.85,range:25},horse:{name:'騎兵',speed:29,power:1.6,range:30},engineer:{name:'工程',speed:11,power:.4,range:190}};
export const FORMATIONS={normal:'常陣',shield:'盾陣',dense:'密集陣',loose:'疏散陣',charge:'衝鋒'};
export const ORDERS={escort:'掩護友軍',build:'架橋／修橋',demolish:'拆橋',move:'行軍',attack:'攻擊',scout:'偵察',rest:'休整',encircle:'封鎖',fire:'火攻',retreat:'撤回',guard:'護糧',intercept:'攔截',ambush:'埋伏'};
const d=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),clamp=(n,l,h)=>Math.max(l,Math.min(h,n));
const mk=(id,name,type,n,x,y,side,general,trait)=>({id,name,type,n,max:n,x,y,side,general,trait,morale:88,fatigue:0,cohesion:100,formation:'normal',stance:'standard',retreatAt:30,order:null,pending:[],plan:[],status:'待命',equipment:'catapult',ladder:false,loss:0,wounded:0,routed:false,stats:{since:0,inflicted:0,kills:0,wallDamage:0,materialDamage:0,ambushes:0}});
function baseGame(role='attack'){
 const units=[mk('a1','第一重步營','heavy',1200,420,625,'attack','韓烈','沉著'),mk('a2','第二槍兵營','spear',1000,535,640,'attack','鄭武','堅守'),mk('a3','第三弓兵營','bow',800,435,675,'attack','沈弦','善射'),mk('a4','第四輕步營','light',700,610,610,'attack','陸遙','輕捷'),mk('a5','第五騎兵營','horse',500,670,690,'attack','趙驍','勇猛'),mk('a6','第六工程營','engineer',600,535,695,'attack','墨衡','巧匠'),mk('d1','南城守備','spear',800,490,450,'defend','周靖','堅守'),mk('d2','東城弓隊','bow',300,677,310,'defend','程羽','善射'),mk('d3','西城守備','heavy',400,313,315,'defend','吳忠','沉著'),mk('d4','北城守備','bow',300,485,180,'defend','李平','善射'),mk('d5','城內預備隊','heavy',800,590,255,'defend','許策','沉著')];
 return {version:1,difficulty:role==='defend'?'recruit':'standard',role,t:0,speed:0,lastSpeed:1,units,walls:['south','east','west','north'].map(id=>({id,...LOCS[id],hp:100,burning:0})).concat([{id:'eastwall',name:'東牆段',x:690,y:390,hp:100,burning:0},{id:'southwall',name:'南牆段',x:395,y:465,hp:100,burning:0}]),points:['barracks','market','grain','office'].map(id=>({id,...LOCS[id],progress:0,owner:'defend'})),intel:{east:{low:250,high:450,time:-120,confidence:2,note:'城頭兵力偏少，城內尚未查明'},south:{low:700,high:1000,time:0,confidence:3,note:'南門重兵設防'},west:{low:300,high:600,time:-180,confidence:2,note:'守軍動向不明'},north:{low:250,high:500,time:-120,confidence:2,note:'山地遮蔽視野'}},supplies:{attack:100,defend:100},campHp:100,grainHp:100,convoys:[{id:1,x:620,y:785,hp:100}],convoyCount:1,weather:'晴',night:false,logs:[{t:0,type:'advice',text:role==='attack'?'軍師：南門守軍最多。東門似乎薄弱，但城內尚未查明。可派輕步營前往北嶺。':'軍師：援軍將於四十五分鐘後抵達。保住官署與糧倉，適時出城截糧。'}],events:{},revealed:false,scoutProgress:0,spy:0,spyCooldown:0,enemyMorale:88,ended:null,tutorial:0,alert:null,stats:{commands:0,convoysLost:0,breaches:0},seed:4816};
}
export function log(g,text,type='info',major=false){g.logs.unshift({t:Math.floor(g.t),text,type});g.logs=g.logs.slice(0,70);if(major){g.speed=0;g.alert=text;}}
export function targets(g){return [...g.walls,...g.points,{id:'hill',...locations(g).hill},{id:'camp',...locations(g).camp},{id:'road',...locations(g).road},{id:'bridge',...locations(g).bridge},{id:'pontoon',name:'浮橋施工點',x:geometry(g).pontoon,y:565},{id:'southwatch',...locations(g).southwatch},{id:'westwatch',...locations(g).westwatch}].filter(p=>!geometry(g).noRiver||!['bridge','pontoon'].includes(p.id));}
export function issue(g,id,action,target,opts={}){
 const u=g.units.find(u=>u.id===id);if(!u||u.n<1||u.routed||g.ended||!ORDERS[action])return false;
 const p=typeof target==='string'?commandTargets(g,u.side).find(p=>p.id===target):target;
 const error=orderError(g,u,action,p);if(error){g.orderError=error;return false;}g.orderError=null;
 const allyId=action==='escort'?p?.allyId:null;const enemyId=action==='escort'?null:p?.unitId||opts.enemyId||null;const foe=enemyId?g.units.find(v=>v.id===enemyId):null;
 if(enemyId&&(!foe||foe.side===u.side||foe.n<=0||!canSee(g,u.side,foe)))return false;
 if(action==='intercept'&&!enemyId)return false;
 if(action==='ambush'&&p?.unitId)return false;
 if(p?.unitId&&!['attack','intercept'].includes(action))return false;
 if(!p&& !['rest','retreat','guard'].includes(action))return false;
 if(action==='encircle'&&!['south','east','west','north'].includes(p?.id))return false;
 const delay=Math.round(clamp(5+d(u,g.role==='attack'?locations(g).camp:locations(g).office)/26+(u.fatigue>60?5:0),5,30));
 const order={action,allyId,enemyId,anchor:{x:u.x,y:u.y},target:p?{id:p.id,x:p.x,y:p.y,name:p.name}:null,delay,formation:opts.formation??u.formation,stance:opts.stance??u.stance,equipment:opts.equipment??u.equipment,retreatAt:opts.retreatAt??u.retreatAt,wait:Number(opts.wait)||0,trigger:opts.trigger??'now',triggerUnit:opts.triggerUnit??null};
 if(opts.queue)u.plan.push(order);else{u.pending=[{...order,eta:g.t+delay}];u.plan=[];}
 g.stats.commands++;g.tutorial=Math.max(g.tutorial,1);log(g,`${u.name}：${opts.queue?'加入協同計畫':'傳令中'} · ${ORDERS[action]}${p?' '+p.name:''}（${delay}秒）`);return true;
}
function activate(g,u,o){u.order={...o,started:g.t,active:0};u.formation=o.formation;u.stance=o.stance;u.equipment=o.equipment;u.retreatAt=o.retreatAt;u.status=ORDERS[o.action];u.ladder=false;u.order.anchor={x:u.x,y:u.y};}
function inside(p,g){return cityInside(p,g);}
function walk(g,u,target,dt){let speed=TYPES[u.type].speed*(1-u.fatigue*.004)*(u.formation==='shield'?.65:u.formation==='charge'?1.5:1)*(g.weather==='雨'?.7:1);if(u.type==='horse'&&u.x>710&&u.y<180)speed*=.45;const before={x:u.x,y:u.y};const arrived=moveAlongRoute(g,u,target,dt,speed);if(d(before,u)>.001){u.fatigue=clamp(u.fatigue+dt*(u.formation==='charge'?.18:.035),0,100);u.cohesion=clamp((u.cohesion??100)+dt*(u.formation==='charge'?-.25:.06),20,100);}return arrived;}

export function hurt(g,u,amount,shock=1,source=null){let hit=Math.min(u.n,Math.max(0,amount));if(u.n-hit<1)hit=u.n;attributeLoss(g,u,hit,source);u.n-=hit;u.loss+=hit;u.wounded+=hit*.57;u.morale=clamp(u.morale-hit/u.max*145*shock*(g.role==='defend'&&(g.difficulty??'recruit')==='recruit'&&u.side==='defend'?.7:1)*(u.trait==='沉著'?.78:1),0,100);if(u.n<1){u.n=0;u.status='失去戰力';u.order=null;}}
function reveal(g){if(g.revealed)return;g.revealed=true;g.tutorial=Math.max(g.tutorial,2);g.intel.east={low:1000,high:1300,time:g.t,confidence:5,note:'斥候確認：城內藏有約八百預備隊。箭矢流向與城頭人數不符。'};log(g,'斥候急報：東門後方發現伏兵！城头三百人只是誘餌。','danger',true);}
export function battleReport(g){
 const report={};for(const side of ['attack','defend']){const army=g.units.filter(u=>u.side===side),initial=Math.round(army.reduce((sum,u)=>sum+u.max,0)),survivors=Math.max(0,Math.min(initial,Math.round(army.reduce((sum,u)=>sum+u.n,0)))),losses=initial-survivors,wounded=Math.max(0,Math.min(losses,Math.round(army.reduce((sum,u)=>sum+u.wounded,0))));report[side]={initial,survivors,losses,wounded,dead:losses-wounded};}report.attack.kills=report.defend.dead;report.defend.kills=report.attack.dead;report.units=unitReport(g,report);return report;
}
function finish(g,result,reason){if(g.ended)return;reason=reason.replaceAll('青石城',g.city||'青石城');g.speed=0;const report=battleReport(g),own=report[g.role];g.ended={result,reason,time:g.t,survivors:own.survivors,dead:own.dead,wounded:own.wounded,report};log(g,reason,result==='victory'?'success':'danger');}

export function surrender(g){if(g.ended)return false;if(g.role==='attack'){const m=g.units.filter(u=>u.side==='defend').reduce((a,u)=>a+u.morale,0)/g.units.filter(u=>u.side==='defend').length;if(g.supplies.defend<18||m<26||g.points.find(p=>p.id==='office').owner==='attack'){finish(g,'victory','守將接受勸降，青石城歸附。');return true;}log(g,'勸降使者回報：守軍仍有糧秣與戰意，拒絕開城。','advice');g.supplies.attack=Math.max(0,g.supplies.attack-1);return false;}finish(g,'defeat','你下令開城投降，保存了餘部。');return true;}
export function withdraw(g){finish(g,'defeat','主帥下令撤軍，青石城之戰結束。');}
export function spy(g){if(g.spyCooldown>g.t||g.spy||g.ended)return false;g.spy=60;g.spyCooldown=g.t+300;g.supplies[g.role]=Math.max(0,g.supplies[g.role]-3);log(g,'密探已出發，六十秒後回報（消耗三份補給）。');return true;}
function ai(g){if(g.role==='attack')defenderAI(g);const enemy=g.role==='attack'?'defend':'attack';for(const u of g.units.filter(u=>u.side===enemy&&u.n>0&&!u.routed)){
 if(g.role==='attack'){continue; }else if(g.level===3&&['a4','a7','a8','a9'].includes(u.id)&&g.t>120){const id={a4:'north',a7:'east',a8:'south',a9:'west'}[u.id];if(u.order?.action!=='encircle')u.order={action:'encircle',target:{id,...locations(g)[id]},started:g.t};continue;}else if(g.level===2&&u.type==='engineer'&&(g.bridges?.bridge??0)<100){if(u.order?.action!=='build')u.order={action:'build',target:{id:'bridge',...locations(g).bridge},started:g.t};continue;}else if(!u.order||u.order.action==='build'&&u.order.complete){const recruit=(g.difficulty??'recruit')==='recruit';const starts=recruit?{a1:240,a2:420,a3:120,a4:360,a5:840,a6:180}:{a1:70,a2:180,a3:30,a4:120,a5:420,a6:60};if(g.t<(starts[u.id]??480)){u.status='部署中';continue;}u.order={action:u.type==='engineer'?'attack':u.type==='light'?'scout':'attack',target:{id:u.type==='light'?'hill':'south',...locations(g)[u.type==='light'?'hill':'south']},started:g.t};}
 if(g.role==='defend'&&g.walls.some(w=>w.hp<=0)&&u.type!=='engineer'){const objective=g.points.find(p=>p.id==='office').owner==='attack'?(u.id==='a1'?'office':g.level===3?'barracks':g.level===2?'grain':u.id==='a4'?'grain':'market'):'office';if(u.order?.target?.id!==objective)u.order={action:'attack',target:{id:objective,...locations(g)[objective]},started:g.t};}
 }}
export function tick(g,dt=1){if(g.ended)return;ensureTelemetry(g);g.bridges??={bridge:100,pontoon:0};g.t+=dt;detectAmbushes(g);for(const u of g.units){u.engagingId=null;u.engagingWallId=null;u.underAttackBy=[];}
 if(g.t>300&&!g.events.rain){g.events.rain=true;g.weather='雨';log(g,'天候轉雨：遠射效率與行軍速度下降，火勢減弱。','advice',true);}if(g.t>600&&g.weather==='雨'){g.weather='霧';log(g,'雨歇起霧：視距縮短，情報更容易過時。','advice');}if(g.t>900&&g.weather==='霧'){g.weather='晴';log(g,'濃霧散去，恢復正常視距。');}g.night=g.t>=1200&&g.t<1800;
 if(g.t>=1200&&!g.events.night){g.events.night=true;log(g,'入夜：偵察距離下降，留意敵軍突圍。','advice',true);}
 if(g.spy>0){g.spy-=dt;if(g.spy<=0){if(g.role==='attack'){reveal(g);for(const u of g.units.filter(u=>u.side==='defend'&&u.order?.action==='ambush'))exposeAmbush(g,u,'密探');}else log(g,'密探：攻軍工程營正部署南門，後方糧營缺乏重兵保護。','success',true);}}
 ai(g);updateObservations(g);
 const blockers=g.units.filter(u=>u.side==='attack'&&u.n>=250&&!u.routed&&u.order?.action==='encircle'&&u.order.arrived);const effectiveBlockers=blockers.filter(u=>!g.units.some(e=>e.side==='defend'&&e.n>150&&!e.routed&&d(u,e)<100));const blocked=new Set(effectiveBlockers.map(u=>u.order.target?.id)).size;g.blockadedGates=blocked;if(g.level===3)fortressBlockade(g,effectiveBlockers,dt);
 if(g.level===2){const northClosed=blockers.some(u=>u.order.target?.id==='north'&&!g.units.some(e=>e.side==='defend'&&e.n>150&&!e.routed&&d(u,e)<100));g.northSupplyOpen=!northClosed;if(!northClosed)g.supplies.defend=clamp(g.supplies.defend+dt*.04,0,100);if(g.t>=480&&!g.events.fordOpen){g.events.fordOpen=true;log(g,'洪水退去：東方淺灘恢復通行，可調兵迂迴北門。','advice',true);}}
 g.supplies.attack=clamp(g.supplies.attack-dt*.018,0,100);g.supplies.defend=clamp(g.supplies.defend-dt*(.008+blocked*.026),0,100);
 if(Math.floor(g.t/160)>g.convoyCount-1){g.convoyCount++;g.convoys.push({id:g.convoyCount,x:locations(g).road.x,y:locations(g).road.y,hp:100});}
 for(const c of g.convoys){const dist=d(c,locations(g).camp);if(dist>8){c.x+=(locations(g).camp.x-c.x)/dist*dt*2.8;c.y+=(locations(g).camp.y-c.y)/dist*dt*2.8;}else {g.supplies.attack=clamp(g.supplies.attack+12*(g.campHp/100),0,100);c.hp=0;c.delivered=true;}
 for(const u of g.units.filter(u=>u.side==='defend'&&u.n>0)){if(d(u,c)<60)c.hp-=dt*u.n/65;}
 if(c.hp<=0&&!c.delivered){g.stats.convoysLost++;g.supplies.attack=clamp(g.supplies.attack-7,0,100);log(g,'運糧隊遭截擊！補給損失。','danger',true);}}
 g.convoys=g.convoys.filter(c=>c.hp>0);
 for(const u of g.units){if(u.n<=0)continue;if(u.burning>0){u.burning=Math.max(0,u.burning-dt*(g.weather==='雨'?4:1));hurt(g,u,dt*.65,2,u.burningSource);u.morale=clamp(u.morale-dt*.04,0,100);}u.status=u.routed?'潰退':u.order?(ORDERS[u.order.action]||'待命'):'待命';
 if(u.pending.length&&u.pending[0].eta<=g.t){activate(g,u,u.pending.shift());log(g,`${u.name}已收到軍令。`);}
 if(u.morale<u.retreatAt&&!u.routed){u.routed=true;u.order={action:'retreat',started:g.t};u.pending=[];u.plan=[];u.status='潰退';log(g,`${u.name}士氣崩潰，向後方撤退！`,'danger',u.side===g.role);}
 if(u.plan.length){const next=u.plan[0],ref=g.units.find(v=>v.id===next.triggerUnit);const ready=next.trigger==='now'?(!u.order||u.order.complete):next.trigger==='time'?(g.t-(u.order?.started??0)>=next.wait):next.trigger==='engaged'?(ref?.order?.fighting&&g.t-ref.order.fighting>=next.wait):next.trigger==='arrived'?(ref?.order?.arrived&&g.t-ref.order.arrived>=next.wait):false;if(ready&&!u.pending.length)u.pending.push({...u.plan.shift(),eta:g.t+next.delay});}
 if(g.supplies[u.side]<15){u.morale=clamp(u.morale-dt*.065,0,100);u.fatigue=clamp(u.fatigue+dt*.03,0,100);}
 updateSortie(g,u);
 const o=u.order;
 if(o){const p=o.target;
 if(o.action==='escort'){escort(g,u,o,dt);}
 else if(['build','demolish'].includes(o.action)){bridgeWork(g,u,o,dt);}
 else if(['intercept','ambush'].includes(o.action)||o.enemyId){targetOrder(g,u,o,dt);}
 else if(['rest','retreat','guard'].includes(o.action)){
 const home=u.side==='attack'?locations(g).camp:locations(g).barracks;const arrived=o.action==='rest'||walk(g,u,home,dt);if(arrived){u.fatigue=clamp(u.fatigue-dt*.22,0,100);u.cohesion=clamp((u.cohesion??100)+dt*.25,0,100);u.morale=clamp(u.morale+dt*.06,0,95);u.status=u.routed?'潰退 · 重整中':'休整';if(u.morale>45)u.routed=false;o.complete=u.fatigue<5;}
 }else if(p){
 if(o.action==='scout'){if(walk(g,u,p,dt)){o.arrived??=g.t;u.status='偵察中';if(g.t-o.arrived>18){if(u.side==='attack'&&(p.id==='hill'||p.id==='east'))reveal(g);const id=['east','south','west','north'].includes(p.id)?p.id:'east';if(g.intel[id])g.intel[id].time=g.t;o.complete=true;u.status='觀察中';}}}
 else if(o.action==='encircle'){if(walk(g,u,{x:clamp(p.x+(p.x-(geometry(g).X0+geometry(g).X1)/2)/Math.hypot(p.x-(geometry(g).X0+geometry(g).X1)/2,p.y-(geometry(g).Y0+geometry(g).Y1)/2)*175,20,980),y:clamp(p.y+(p.y-(geometry(g).Y0+geometry(g).Y1)/2)/Math.hypot(p.x-(geometry(g).X0+geometry(g).X1)/2,p.y-(geometry(g).Y0+geometry(g).Y1)/2)*175,20,800)},dt)){o.arrived??=g.t;u.status='封鎖道路';}}
 else if(o.action==='move'){if(walk(g,u,p,dt)){o.arrived??=g.t;o.complete=true;u.status='抵達';}}
 else if(['attack','fire'].includes(o.action)){
 let range=u.type==='engineer'?(u.equipment==='ram'?35:u.equipment==='ladder'?32:190):TYPES[u.type].range;
 const wall=g.walls.find(w=>w.id===p.id),point=g.points.find(q=>q.id===p.id);if(wall&&u.type==='bow')range-=25;if(wall&&u.type==='engineer'&&u.equipment==='tower')range-=30;
 if(point)range=Math.min(range,40);const guard=point?g.units.filter(v=>v.side!==u.side&&v.n>0&&!v.routed&&d(v,point)<90&&canSee(g,u.side,v)).sort((a,b)=>d(a,u)-d(b,u))[0]:null;const approach=guard||p;if(guard)range=combatRange(g,u)*.9;
 if(d(u,approach)>range)walk(g,u,approach,dt);else {o.arrived??=g.t;u.status=o.action==='fire'?'縱火':wall&&u.side==='defend'?'守備中':point?'據點作戰':'就位';if((wall&&u.side==='attack'&&wall.hp>0)||o.action==='fire'){o.fighting??=g.t;u.fatigue=clamp(u.fatigue+dt*.08,0,100);u.status=o.action==='fire'?'縱火':'攻城';}
 if(wall&&u.side==='attack'&&wall.hp>0){let damage=u.type==='engineer'?(u.equipment==='ram'?.4:u.equipment==='catapult'?.23:u.equipment==='ladder'?0:0):u.type==='heavy'?.045:.014;if(g.role==='defend'&&(g.difficulty??'recruit')==='recruit')damage*=.42;u.engagingWallId=wall.id;if(wall.id.includes('wall')&&u.type!=='engineer')damage*=.05;if(g.level===3&&g.isolation>=120&&u.side==='attack')damage*=1.25;damage*=u.n/u.max*(1-u.fatigue*.005)*(g.weather==='雨'?.75:1);if(o.action==='fire'){wall.burning=60;wall.burningSource=u.id;damage*=1.4;}const wallHit=Math.min(wall.hp,dt*damage);wall.hp-=wallHit;u.stats.wallDamage+=wallHit;if(u.type==='engineer'&&u.equipment==='ladder'&&g.t-o.fighting>35){if(!wall.ladderReady){wall.ladderReady=true;log(g,`${wall.name}雲梯已架設，步兵可由此登城。`,'success',true);}u.status='雲梯就位';}
 if(wall.hp<=0){g.stats.breaches++;g.tutorial=Math.max(3,g.tutorial);log(g,`${wall.name}被突破！進城占領官署及另一處據點。`,'success',true);o.complete=true;}}
 if(o.action==='fire'){for(const enemy of g.units.filter(v=>v.side!==u.side&&v.type==='engineer'&&d(u,v)<45)){enemy.burning=45;enemy.burningSource=u.id;}}
 if(o.action==='fire'&&p.id==='camp'&&u.side==='defend'){const materialHit=Math.min(g.campHp,dt*.4);g.campHp-=materialHit;u.stats.materialDamage+=materialHit;g.supplies.attack=clamp(g.supplies.attack-dt*.2,0,100);}
 if(o.action==='fire'&&p.id==='grain'&&u.side==='attack'){const materialHit=Math.min(g.grainHp,dt*.2);g.grainHp-=materialHit;u.stats.materialDamage+=materialHit;g.supplies.defend=clamp(g.supplies.defend-dt*.15,0,100);}
 if(point&&point.owner===u.side)o.complete=true;
 }
 }
 }
 }
 if(!u.routed&&!(o?.action==='ambush'&&!o.sprung)){
 const range=combatRange(g,u),requested=o?.enemyId?g.units.find(v=>v.id===o.enemyId):null;
 const candidates=g.units.filter(v=>v.side!==u.side&&v.n>0&&d(u,v)<range&&canSee(g,u.side,v)&&canHit(g,u,v));
 const escorted=o?.action==='escort'?g.units.find(v=>v.id===o.allyId):null;const choices=escorted?candidates.filter(e=>d(e,escorted)<130):candidates;const enemy=requested&&choices.includes(requested)?requested:choices.sort((a,b)=>(escorted?d(a,escorted)-d(b,escorted):d(u,a)-d(u,b)))[0];
 if(enemy&&(u.stance!=='cautious'||d(u,enemy)<45||['attack','intercept','ambush'].includes(o?.action))){
 const frontage=u.side==='attack'&&inside(u,g)&&!['bow','engineer'].includes(u.type)&&g.walls.some(w=>(w.hp<=0||w.ladderReady)&&d(u,w)<105)?Math.min(u.n,550):u.n;let power=frontage/1000*TYPES[u.type].power*(.3+u.morale/100)*(.9-u.fatigue*.005)*(.5+(u.cohesion??100)/200);
 if(u.type==='engineer'&&u.equipment==='tower')power*=2.5;if(u.type==='engineer'&&u.equipment==='shieldcart')power*=.2;
 const ranged=u.type==='bow'||u.type==='engineer';if(ranged){power*=g.weather==='雨'?.55:1;power*=enemy.formation==='shield'?.48:enemy.formation==='loose'?.62:enemy.formation==='dense'?1.3:1;if(g.units.some(a=>a.side===enemy.side&&a.type==='engineer'&&a.equipment==='shieldcart'&&d(a,enemy)<90))power*=.65;}else{power*=u.formation==='dense'?1.2:u.formation==='loose'?.72:1;if(u.type==='horse'){power*=u.formation==='charge'?1.5:1;if(enemy.type==='spear'&&enemy.fatigue<45&&!enemy.routed&&enemy.morale>55)power*=.45;else if(enemy.routed||enemy.fatigue>65)power*=1.6;}}
 if(g.role==='attack'&&u.side==='defend')power*=1.2;
 if(enemy.side==='defend'&&inside(enemy,g)&&!inside(u,g))power*=nearWall(g,enemy)?(ranged?.38:.6):.85;
 if(g.role==='defend'&&(g.difficulty??'recruit')==='recruit'&&u.side==='attack')power*=.7;
 if(o?.ambushUntil>g.t)power*=1.8;
 power*=.55+.45*Math.min(1,g.supplies[u.side]/50);if(u.shakenUntil>g.t)power*=.45;
 if(u.side==='defend'&&inside(u,g)&&g.supplies.defend>35&&g.points.some(p=>p.owner==='defend'&&d(u,p)<100))power*=1.3;
 if(enemy.side==='defend'&&inside(enemy,g)&&g.supplies.defend>35&&g.points.some(p=>p.owner==='defend'&&d(enemy,p)<100))power*=.75;
 if(g.level===3&&g.isolation>=120&&u.side==='defend')power*=.8;if(g.level===3&&enemy.side==='attack'&&enemy.order?.action==='encircle'&&enemy.order.arrived&&enemy.n>=250)power*=.65;hurt(g,enemy,power*dt*2,u.type==='horse'?1.3:1,u);u.fatigue=clamp(u.fatigue+dt*.045,0,100);if(o)o.fighting??=g.t;u.status='交戰';u.engagingId=enemy.id;enemy.underAttackBy.push(u.id);
 }else if(!(g.role==='defend'&&u.side==='defend')&&u.stance==='aggressive'&&(!o||o.complete)){const near=g.units.find(v=>v.side!==u.side&&v.n>0&&canSee(g,u.side,v)&&canHit(g,u,v)&&d(u,v)<100);if(near)walk(g,u,near,dt);}
 if(!enemy&&u.side==='defend'&&inside(u,g)){u.fatigue=clamp(u.fatigue-dt*.06,0,100);}
 }

 }
 for(const w of g.walls){if(w.burning>0){w.burning-=dt;const prev=w.hp;w.hp=Math.max(0,w.hp-dt*(g.weather==='雨'?.025:.09));const burner=g.units.find(u=>u.id===w.burningSource);if(burner?.stats)burner.stats.wallDamage+=prev-w.hp;if(prev>0&&w.hp===0){g.stats.breaches++;log(g,`${w.name}被大火摧毀！`,'danger',true);}}}
 for(const p of g.points){const atk=g.units.filter(u=>u.side==='attack'&&u.n>0&&!u.routed&&inside(u,g)&&d(u,p)<55).reduce((a,u)=>a+u.n,0);const def=g.units.filter(u=>u.side==='defend'&&u.n>0&&!u.routed&&inside(u,g)&&d(u,p)<90).reduce((a,u)=>a+u.n,0);p.contested=atk>0&&def>=80;if(atk>0&&def<80){p.progress=clamp(p.progress+dt*Math.min(g.role==='defend'&&(g.difficulty??'recruit')==='recruit'?.28:.75,(atk-def)/700),0,100);}else if(def>=80)p.progress=clamp(p.progress-dt*.8,0,100);if(p.progress>=100&&p.owner!=='attack'){p.owner='attack';g.tutorial=4;log(g,`${p.name}已被攻軍占領。`,'danger',true);}if(p.progress<=0)p.owner='defend';}
 if(g.units.filter(u=>u.side==='attack').every(u=>u.n<20||u.routed))finish(g,g.role==='attack'?'defeat':'victory','攻軍全線潰退，青石城守住了。');
 const office=g.points.find(p=>p.id==='office');if(office.owner==='attack'&&(g.level>=2?g.points.find(p=>p.id===(g.level===3?'barracks':'grain')).owner==='attack':g.points.filter(p=>p.owner==='attack').length>=2))finish(g,g.role==='attack'?'victory':'defeat','官署與城內要地失守，青石城易主。');
 if(g.supplies.defend<=0&&g.units.filter(u=>u.side==='defend').every(u=>u.morale<35))finish(g,g.role==='attack'?'victory':'defeat','守軍糧盡、軍心瓦解，開城投降。');
 if(g.t>=2700)finish(g,g.role==='attack'?'defeat':'victory','守軍援軍抵達。攻軍撤退，青石城解圍。');
 if(g.speed===20&&g.units.some(u=>u.engagingId||u.engagingWallId)){g.speed=0;log(g,'部隊接戰，已停止高速時間。','danger',true);}
}
export function canSee(g,side,u){if(u.side===side)return true;const near=g.units.some(a=>a.side===side&&a.n>0&&d(a,u)<(g.weather==='霧'||g.night?150:260));const lookout=g.units.some(a=>a.side===side&&a.n>0&&a.order?.action==='scout'&&d(a,locations(g).hill)<25&&d(a,u)<(g.night||g.weather==='霧'?260:590));if(u.id==='d5'&&!g.revealed&&side==='attack'&&!near)return false;if(u.order?.action==='ambush'&&u.order.armed&&!u.order.sprung&&!(u.detectedUntil>g.t))return g.units.some(a=>a.side===side&&a.n>0&&d(a,u)<(a.order?.action==='scout'?180:70));return near||lookout;}
export function visible(g,u){return canSee(g,g.role,u);}
export function commandTargets(g,side=g.role){return [...targets(g),...g.units.filter(u=>u.side===side&&u.n>0).map(u=>({id:u.id,allyId:u.id,name:'友・'+u.name,x:u.x,y:u.y})),...g.units.filter(u=>u.side!==side&&u.n>0&&canSee(g,side,u)).map(u=>({id:u.id,unitId:u.id,name:'敵・'+u.name,x:u.x,y:u.y}))];}
export function nearWall(g,u){return inside(u,g)&&g.walls.some(w=>w.hp>0&&d(u,w)<85);}
export function combatRange(g,u){return (u.type==='engineer'?(u.equipment==='ram'||u.equipment==='ladder'?30:190):TYPES[u.type].range+(u.type==='bow'&&u.side==='defend'&&nearWall(g,u)?60:0))*(g.weather==='霧'?.65:1)*(g.night?.7:1);}
export function canHit(g,a,b){if(['bow','engineer'].includes(a.type))return true;return legalSegment(g,a,a,b);}
function targetOrder(g,u,o,dt){
 if(o.action==='ambush'&&!o.sprung){if(!o.armed){if(walk(g,u,o.target,dt)){o.arrived??=g.t;o.armed=g.t;}u.status='前往伏擊點';return;}
 u.status='埋伏待命';u.fatigue=clamp(u.fatigue-dt*.12,0,100);
 const victim=g.units.filter(v=>v.side!==u.side&&v.n>0&&(!o.enemyId||v.id===o.enemyId)&&d(u,v)<=90&&canSee(g,u.side,v)&&canHit(g,u,v)).sort((a,b)=>d(u,a)-d(u,b))[0];
 if(victim&&g.t-o.armed>=10){o.enemyId=victim.id;o.sprung=true;o.triggeredAt=g.t;const surprise=!(u.detectedUntil>g.t)&&g.supplies[u.side]>35;o.ambushUntil=surprise?g.t+20:0;o.anchor={x:u.x,y:u.y};u.stats.ambushes++;if(surprise){hurt(g,victim,Math.min(170,victim.n*.14),1.8,u);victim.morale=clamp(victim.morale-25,0,100);victim.cohesion=clamp((victim.cohesion??100)-45,0,100);victim.shakenUntil=g.t+50;}log(g,surprise?`${u.name}伏擊${victim.name}！陣型受挫，前五十秒戰力下降。`:`${u.name}發起伏擊，但位置已暴露或補給不足，未獲突襲優勢。`,'danger',true);}
 else return;
 }
 const foe=g.units.find(v=>v.id===o.enemyId);
 if(!foe||(foe.n<=0&&canSee(g,u.side,foe))){u.status='目標已失去戰力';o.complete=true;return;}
 if(foe.n>0&&canSee(g,u.side,foe)){
 const old=o.lastSeen,elapsed=old?g.t-old.t:0;
 const vx=elapsed>0?(foe.x-old.x)/elapsed:0,vy=elapsed>0?(foe.y-old.y)/elapsed:0;
 o.lastSeen={x:foe.x,y:foe.y,t:g.t};o.lost=false;
 const lead=o.action==='intercept'?Math.min(4,d(u,foe)/TYPES[u.type].speed):0;
 const leadX=clamp(vx*lead,-60,60),leadY=clamp(vy*lead,-60,60);
 o.target={id:foe.id,name:'敵・'+foe.name,x:clamp(foe.x+leadX,20,980),y:clamp(foe.y+leadY,20,800)};
 if(['intercept','ambush'].includes(o.action)&&d(foe,o.anchor)>220){u.status='停止追擊 · 超出攔截區';return;}
 if(d(u,foe)>combatRange(g,u)*.9||!canHit(g,u,foe)){let aim=o.target;if(['bow','engineer'].includes(u.type)){const r=combatRange(g,u)*.85;const spots=Array.from({length:16},(_,i)=>({x:foe.x+Math.cos(i*Math.PI/8)*r,y:foe.y+Math.sin(i*Math.PI/8)*r})).filter(p=>p.x>20&&p.x<980&&p.y>20&&p.y<800).sort((a,b)=>d(u,a)-d(u,b));aim=spots.find(p=>findRoute(g,u,p))||aim;}u.status=o.action==='intercept'?'機動攔截':o.action==='ambush'?'伏擊追擊':'追蹤目標';walk(g,u,aim,dt);}else{u.status='目標接戰';o.arrived??=g.t;}
 }else{if(!o.lost){o.lost=true;log(g,`${u.name}失去指定敵軍視野，僅前往最後確認位置。`,'advice');}if(walk(g,u,o.lastSeen||o.target,dt)){u.status='失去目標 · 原地警戒';}else if(!u.status.startsWith('道路受阻'))u.status='搜索最後位置';}
}

function defenderAI(g){
 if(g.t<(g.nextDefenseDecision??0))return;g.nextDefenseDecision=g.t+8;
 const defenders=g.units.filter(u=>u.side==='defend'&&u.n>0&&!u.routed),seen=g.units.filter(u=>u.side==='attack'&&u.n>0&&!u.routed&&canSee(g,'defend',u));
 const intruders=seen.filter(e=>inside(e,g)),sectors=g.walls.map(w=>({wall:w,foes:seen.filter(e=>d(e,w)<260),score:seen.reduce((sum,e)=>sum+(d(e,w)<260?e.n*(e.type==='engineer'?1.8:1)*(1-d(e,w)/360):0),0)+(seen.some(e=>d(e,w)<260)?(100-w.hp)*4+(w.hp<=0?300:0):0)})).sort((a,b)=>b.score-a.score);
 const main=sectors[0],second=sectors.find(s=>s.wall.id!==main.wall.id&&d(s.wall,main.wall)>150&&s.score>500);
 const set=(u,action,p,enemyId=null)=>{if(!u)return;const key=action+':'+(enemyId||p.id||Math.round(p.x)+','+Math.round(p.y));if(u.aiTask===key&&u.order&&u.order.action===action&&u.order.target?.id===p.id&&!u.order.complete)return;u.aiTask=key;u.order={action,target:{...p},enemyId,anchor:{x:u.x,y:u.y},started:g.t,formation:u.type==='bow'?'loose':'dense'};u.formation=u.order.formation;u.nav=null;};
 const post=(w,depth=28)=>{const [out,inn]=portalPoints(w);const dx=inn.x-w.x,dy=inn.y-w.y;return {x:w.x+dx/24*depth,y:w.y+dy/24*depth,name:w.name+'內側防線',id:'post-'+w.id+'-'+depth};};
 if(main.score<150&&!intruders.length)return;
 const reserve=defenders.find(u=>u.id==='d5');
 if(reserve?.order?.action==='ambush'&&reserve.order.sprung&&g.t-(reserve.order.triggeredAt??0)<100){}
 else if(intruders.length){const threat=intruders.sort((a,b)=>(b.n/(d(b,locations(g).office)+40))-(a.n/(d(a,locations(g).office)+40)))[0];set(reserve,'attack',{x:threat.x,y:threat.y,name:threat.name,id:threat.id},threat.id);}
 else {const ambushPost=post(main.wall,95);set(reserve,'ambush',ambushPost);}
 const melee=defenders.filter(u=>['d1','d3','d7'].includes(u.id));for(const u of melee){if(u.sortie)continue;if(u.morale<52||u.fatigue>65||(u.recovering&&(u.morale<65||u.fatigue>25))){u.recovering=true;set(u,'rest',post(main.wall,70));continue;}u.recovering=false;const local=intruders.filter(e=>d(e,u)<180).sort((a,b)=>d(a,u)-d(b,u))[0];if(local){set(u,'attack',{x:local.x,y:local.y,name:local.name,id:local.id},local.id);continue;}const home=u.id==='d3'?'west':'south';const homeSector=sectors.find(s=>s.wall.id===home);const assigned=homeSector.score>350?homeSector:second&&main.score>second.score*1.8?(u.id==='d3'?main:second):main;const atGate=assigned.foes.filter(e=>!inside(e,g)&&d(e,assigned.wall)<220).sort((a,b)=>(a.type==='engineer'?-1000:0)+d(a,u)-((b.type==='engineer'?-1000:0)+d(b,u)))[0];if(atGate&&safeSortie(g,u,atGate,assigned.wall)&&u.morale>48&&u.fatigue<65&&(g.t>(u.sortieCooldown??0)||d(atGate,assigned.wall)<65)){beginSortie(g,u,atGate,assigned.wall);continue;}set(u,'move',post(assigned.wall,u.id==='d3'?24:28));}
 const bows=defenders.filter(u=>u.type==='bow'),covered=[];for(let i=0;i<bows.length;i++){const u=bows[i],sector=sectors.filter(s=>s.foes.length).sort((a,b)=>b.score/(covered.some(w=>d(w,b.wall)<150)?4:1)-a.score/(covered.some(w=>d(w,a.wall)<150)?4:1))[0]||main;covered.push(sector.wall);const p=post(sector.wall,18);if(['east','west'].includes(sector.wall.id)||sector.wall.id==='eastwall')p.y+=i===0?-38:38;else p.x+=i===0?-38:38;p.id+='-bow'+i;set(u,'move',p);}
 if(g.lastDefenseSector!==main.wall.id&&main.score>700){g.lastDefenseSector=main.wall.id;log(g,`斥候觀察：守軍正向${main.wall.name}集中增援。`,'advice',true);}
}

function exposeAmbush(g,u,source){const newly=!(u.detectedUntil>g.t);u.detectedUntil=g.t+180;if(newly){log(g,`${source}發現${u.name}的伏擊陣地。三分鐘內其突襲優勢失效。`,'success',true);}}
function detectAmbushes(g){for(const u of g.units.filter(u=>u.n>0&&u.order?.action==='ambush'&&!u.order.sprung)){const scout=g.units.find(a=>a.side!==u.side&&a.n>0&&a.order?.action==='scout'&&(d(a,u)<180||(d(a,locations(g).hill)<25&&d(a,u)<590&&!g.night&&g.weather!=='霧')));if(scout)exposeAmbush(g,u,'斥候');}}
function beginSortie(g,u,enemy,wall){const origin=portalPoints(wall)[1];u.sortie={origin,wallId:wall.id,until:g.t+100,phase:'out',resume:u.order?{...u.order}:null};u.order={action:'attack',enemyId:enemy.id,target:{x:enemy.x,y:enemy.y,id:enemy.id,name:enemy.name},anchor:origin,started:g.t};u.formation='dense';u.nav=null;log(g,`${u.name}由${wall.name}出城迎擊${enemy.name}，可攔截其回城路線。`,'danger',true);}
function updateSortie(g,u){if(g.role==='defend'&&u.side==='defend'){if(u.sortie){u.order=u.sortie.resume;u.sortie=null;u.nav=null;}return;}if(u.sortie){const s=u.sortie,foe=g.units.find(e=>e.id===u.order?.enemyId);if(u.routed||u.pending.length){u.sortie=null;u.sortieCooldown=g.t+120;return;}if(s.phase==='out'&&(g.t>=s.until||u.morale<45||u.fatigue>70||!foe||foe.n<=0||d(foe,s.origin)>290)){s.phase='return';u.order={action:'move',target:{...s.origin,name:'回城整隊'},started:g.t};u.nav=null;}if(s.phase==='return'&&d(u,s.origin)<8){u.sortie=null;u.sortieCooldown=g.t+25;u.order=s.resume;u.aiTask=null;u.nav=null;}return;}
 if(u.side!=='defend'||g.role!=='defend'||!['heavy','spear','light'].includes(u.type)||u.routed||u.pending.length||u.stance==='cautious'||u.morale<48||u.fatigue>65||g.t<(u.sortieCooldown??0))return;
 const o=u.order;if(o&&(o.enemyId||['ambush','rest','retreat','intercept','fire'].includes(o.action)||(o.action==='move'&&!o.complete)))return;const wall=g.walls.filter(w=>['north','south','east','west'].includes(w.id)).sort((a,b)=>d(u,a)-d(u,b))[0];if(!wall||d(u,wall)>60)return;const enemy=g.units.filter(e=>e.side==='attack'&&e.n>0&&!e.routed&&!inside(e,g)&&canSee(g,u.side,e)&&d(e,wall)<210).sort((a,b)=>d(a,u)-d(b,u))[0];if(enemy)beginSortie(g,u,enemy,wall);}

export function updateObservations(g){g.wallIntel??={};for(const w of g.walls){const seen=g.role==='defend'||g.units.some(u=>u.side===g.role&&u.n>0&&d(u,w)<(g.weather==='霧'||g.night?150:260));if(seen)g.wallIntel[w.id]={hp:w.hp,time:g.t};}
if(g.role!=='attack')return;for(const id of ['north','south','east','west']){const w=locations(g)[id],seen=g.units.some(u=>u.side==='attack'&&u.n>0&&(d(u,w)<(g.weather==='霧'||g.night?150:260)||(u.order?.action==='scout'&&d(u,locations(g).hill)<25&&d(u,w)<590&&!g.night&&g.weather!=='霧')));if(!seen)continue;const enemies=g.units.filter(u=>u.side==='defend'&&u.n>0&&d(u,w)<110&&canSee(g,'attack',u));const n=enemies.reduce((a,u)=>a+u.n,0);g.intel[id]={low:Math.max(0,Math.floor(n*.85/50)*50),high:n?Math.ceil(n*1.15/50)*50:0,time:g.t,confidence:4,note:'目前目視城門周邊兵力；不包含未發現伏兵或其他城區。',morale:enemies.length?(enemies.reduce((a,u)=>a+u.morale,0)/enemies.length<40?'可見部隊動搖':'可見部隊尚穩'):'未見守軍'};}}

export function orderError(g,u,action,p){if(g.level===3&&['build','demolish'].includes(action))return '本關為陸路要塞，沒有可架設或拆除的橋梁。';if(action==='escort'){if(!p?.allyId||p.allyId===u.id)return '掩護須選擇另一支己方部隊。';return null;}if(p?.allyId)return '友軍目標只適用於掩護命令。';
 if(['build','demolish'].includes(action)){if(!['bridge','pontoon'].includes(p?.id))return '請選石橋或浮橋施工點。';if(action==='build'&&(u.side!=='attack'||u.type!=='engineer'))return '只有攻方工程營可架橋／修橋。';if(action==='demolish'&&(u.side!=='defend'||!['heavy','spear','light','engineer'].includes(u.type)))return '拆橋需要守方步兵或工程部隊。';if((g.bridges?.[p.id]??(p.id==='bridge'?100:0))===(action==='build'?100:0))return action==='build'?'橋梁已可通行。':'此處沒有可拆除的橋梁。';}
 if(['attack','fire'].includes(action)){const point=g.points.find(q=>q.id===p?.id),wall=g.walls.find(w=>w.id===p?.id);if(point?.owner===u.side)return '不可攻擊己方占領的據點；請改用行軍部署防守。';if(wall&&u.side==='defend')return '不可攻擊己方城防；請用行軍部署，或指定敵軍攻擊。';if(!p?.unitId&&!point&&!wall&&!(action==='fire'&&p?.id==='camp'&&u.side==='defend'))return '此目標不可攻擊；橋梁請使用架橋／拆橋軍令。';if(action==='fire'&&point&&point.id!=='grain')return '此據點不能火攻；請改用攻擊／占領。';}return null;}
function safeSortie(g,u,foe,wall){const threats=g.units.filter(e=>e.side==='attack'&&e.n>0&&!e.routed&&canSee(g,'defend',e)&&d(e,foe)<150).reduce((a,e)=>a+e.n*(e.type==='horse'?1.3:e.type==='engineer'?.4:1),0);const support=g.units.filter(e=>e.side==='defend'&&e.n>0&&!e.routed&&e.morale>50&&d(e,wall)<180).reduce((a,e)=>a+e.n*(e.type==='bow'?.7:1),0);return support>=threats*1.1&&u.n>u.max*.45;}
function bridgeWork(g,u,o,dt){const id=o.target.id,x=geometry(g)[id],bank={x,y:u.y<565?520:610};if(d(u,bank)>12){walk(g,u,bank,dt);return;}if(o.complete){u.status='橋梁工程完成';return;}if(g.units.some(e=>e.side!==u.side&&e.n>0&&!e.routed&&d(e,u)<65)){u.status='工程暫停 · 敵軍接近';return;}const build=o.action==='build';if(build&&g.supplies.attack<=0){u.status='工程暫停 · 缺乏補給';return;}const delta=dt*(build?1:1.25)*u.n/u.max;if(build)g.supplies.attack=Math.max(0,g.supplies.attack-delta*.1);g.bridges[id]=clamp(g.bridges[id]+(build?delta:-delta),0,100);u.status=(build?'架橋':'拆橋')+' '+Math.round(g.bridges[id])+'%';if(g.bridges[id]===(build?100:0)){o.complete=true;log(g,(id==='bridge'?'石橋':'浮橋')+(build?'已可通行。':'已拆除，部隊須改道。'),'advice',true);}}


export function newGame(role='attack',level=1){const g=baseGame(role);g.level=[2,3].includes(level)?level:1;g.city=g.level===2?'臨川城':'青石城';if(g.level===1)return addOpeningStory(g);const counts={a1:1600,a2:1400,a3:1000,a4:800,a5:600,a6:800,d1:1100,d2:500,d3:500,d4:500,d5:1000};for(const u of g.units){u.n=u.max=counts[u.id];}g.bridges={bridge:0,pontoon:0};g.supplies.attack=80;g.supplies.defend=85;g.walls.find(w=>w.id==='north').hp=70;g.logs=[{t:0,type:'advice',text:'臨川渡河戰：石橋已毀，淺灘洪水將於 08:00 退去。先修橋或架浮橋；守軍由北門補糧，北門封鎖成功才會切斷。占領官署與糧倉，或圍城迫降。'}];g.intel.north.note='北門城防老舊，但有補糧道路。';g.intel.south.note='南門重兵守備，不宜無偵察直接強攻。';expandRiver(g);if(g.level===3)makeFortress(g);return addOpeningStory(g);}

export function locations(g){return g.locs||LOCS;}
function expandRiver(g){g.mapRevision=2;g.layout={X0:380,X1:820,Y0:130,Y1:430,bridge:330,pontoon:730,ford:140};g.locs={...LOCS,south:{name:'南門',x:590,y:430},north:{name:'北門',x:630,y:130},west:{name:'西門',x:380,y:280},east:{name:'東門',x:820,y:250},hill:{name:'西嶺觀察點',x:230,y:110},barracks:{name:'兵營',x:480,y:200},market:{name:'市集',x:500,y:320},office:{name:'官署',x:650,y:220},grain:{name:'糧倉',x:740,y:360},southwatch:{name:'南城東射位',x:680,y:400},westwatch:{name:'南城西射位',x:500,y:400},bridge:{name:'石橋',x:330,y:565}};for(const w of g.walls)Object.assign(w,g.locs[w.id]||{x:w.id==='eastwall'?820:460,y:w.id==='eastwall'?365:430});for(const p of g.points)Object.assign(p,g.locs[p.id]);const positions={d1:[590,408],d2:[802,250],d3:[399,280],d4:[630,148],d5:[680,310]};for(const u of g.units)if(positions[u.id])[u.x,u.y]=positions[u.id];
const counts={a1:1200,a2:1000,a3:800,a4:600,a5:500,a6:600,d1:800,d2:450,d3:450,d4:400,d5:600};for(const u of g.units)u.n=u.max=counts[u.id];g.units.push(mk('a7','第七護衛營','spear',600,570,680,'attack','梁慎','堅守'),mk('a8','第八弓兵營','bow',500,720,715,'attack','顧弦','善射'),mk('a9','第九游騎營','horse',400,290,690,'attack','秦越','輕捷'),mk('a10','第十工兵營','engineer',600,350,735,'attack','陶衡','巧匠'),mk('d6','糧倉弓隊','bow',450,742,386,'defend','宋羽','善射'),mk('d7','北門預備營','spear',450,620,180,'defend','趙毅','堅守'));g.logs[0].text='臨川渡河戰：十營共 6,800 人。城池偏東北，西側石橋、東側浮橋、西端淺灘通向不同戰線。先派護衛掩護工兵，再選擇渡河路線；08:00 洪水退去。';}
function escort(g,u,o,dt){const ally=g.units.find(v=>v.id===o.allyId&&v.side===u.side);if(!ally||ally.n<=0){o.complete=true;u.status='掩護結束 · 友軍失去戰力';return;}const foes=g.units.filter(e=>e.side!==u.side&&e.n>0&&!e.routed&&canSee(g,u.side,e)&&d(e,ally)<130&&canHit(g,u,e)).sort((a,b)=>d(a,ally)-d(b,ally));const threat=foes[0];const ranged=['bow','engineer'].includes(u.type);if(threat&&d(u,ally)<150){if(d(u,threat)>combatRange(g,u)*.9)walk(g,u,threat,dt);u.status='掩護接敵 · '+ally.name;}else{const index=g.units.filter(v=>v.order?.action==='escort'&&v.order.allyId===ally.id).findIndex(v=>v.id===u.id);const angle=index*Math.PI*.6;let point={x:ally.x+Math.cos(angle)*35,y:ally.y+(ranged?35:-35)};if(point.y>535&&point.y<595)point.y=ally.y<565?520:610;if(!findRoute(g,u,point))point={x:ally.x,y:ally.y};u.status='跟隨掩護 · '+ally.name;if(d(u,ally)>65||d(u,point)>15)walk(g,u,point,dt);}o.target={id:ally.id,x:ally.x,y:ally.y,name:ally.name};}

function makeFortress(g){g.city='朔風城';g.mapRevision=3;g.layout={X0:240,X1:560,Y0:190,Y1:650,bridge:495,pontoon:650,ford:810,noRiver:true};g.locs={...LOCS,north:{name:'北門',x:390,y:190},south:{name:'南門',x:440,y:650},west:{name:'西門',x:240,y:390},east:{name:'東門',x:560,y:470},hill:{name:'東臺觀察點',x:780,y:170},camp:{name:'東軍糧營',x:865,y:710},road:{name:'後方道路',x:945,y:785},office:{name:'官署',x:395,y:350},barracks:{name:'內城兵營',x:435,y:540},grain:{name:'糧倉',x:330,y:255},market:{name:'馬市',x:325,y:470},southwatch:{name:'南城射位',x:460,y:610},westwatch:{name:'東城射位',x:525,y:475}};for(const w of g.walls){Object.assign(w,g.locs[w.id]||{x:w.id==='eastwall'?560:310,y:w.id==='eastwall'?290:650});w.hp=100;}for(const p of g.points)Object.assign(p,g.locs[p.id]);const defense={d1:[440,625],d2:[540,470],d3:[262,390],d4:[390,212],d5:[420,420],d6:[330,275],d7:[450,520]};let n=0;for(const u of g.units){if(u.side==='attack'){u.x=690+(n%3)*85;u.y=590+Math.floor(n/3)*48;n++;u.n=u.max=({a1:1400,a2:1200,a3:800,a4:600,a5:700,a6:600,a7:700,a8:600,a9:400,a10:600})[u.id];}else{[u.x,u.y]=defense[u.id];u.n=u.max=({d1:900,d2:600,d3:600,d4:500,d5:700,d6:500,d7:400})[u.id];}}g.supplies={attack:75,defend:95};g.isolation=0;g.logs=[{t:0,type:'advice',text:'朔風合圍戰：四條陸路持續送糧。封鎖可截獲補給、建立防禦陣地；同時封住三門 120 秒，可削弱守軍並加快破城。勝利須控制官署與內城兵營，或迫降。'}];for(const i of Object.values(g.intel)){i.time=-120;i.note='城門後方與守軍調度待偵察確認。';}g.convoys=[{id:1,x:945,y:785,hp:100}];}
function fortressBlockade(g,units,dt){const gates=[...new Set(units.map(u=>u.order.target.id))];g.blockadeRoads=gates;const count=gates.length;g.supplies.defend=clamp(g.supplies.defend+dt*((4-count)*.018-count*.025),0,100);g.supplies.attack=clamp(g.supplies.attack+dt*count*.035,0,100);g.isolation=count>=3?Math.min(120,(g.isolation||0)+dt):0;for(const u of units){u.fatigue=clamp(u.fatigue-dt*.1,0,100);if(!g.units.some(e=>e.side==='defend'&&e.n>0&&!e.routed&&d(e,u)<150)&&g.supplies.attack>25)u.morale=clamp(u.morale+dt*.025,0,95);}const isolated=g.isolation>=120;if(isolated!==!!g.isolatedNotice){g.isolatedNotice=isolated;log(g,isolated?'合圍完成：守軍戰力降低 20%，攻方破城效率提高 25%。':'合圍被打斷：持續封鎖三門才能重新取得壓制。','advice',true);}if(isolated)for(const u of g.units.filter(u=>u.side==='defend'&&u.n>0))u.morale=clamp(u.morale-dt*.02,0,100);}
